// Real Bank-15 music/sound-driver player (2026-08-15, direct user
// request "schau dir mal das musik und sound system an und
// entschluessel es" -> "konsolidieren, dokumentieren und in die
// website einbauen"). Every note/duration/octave value shown and
// played here is a REAL, decoded value from MUSIC (js/data/music.js,
// generated by rom-inspector/tools/export_data.lua via src/import/
// MusicDecoder.lua) -- see docs/reverse-engineering/rom-map.md's
// "Audio format -- DECODED" section for the full disassembly trail.
//
// Playback is a real, audible, SIMPLIFIED chiptune rendition: each
// NOTE event becomes a Web Audio square-wave oscillator burst at the
// real GB frequency (via the real period formula, freq_hz = 131072 /
// (2048 - period)) for the real decoded duration (durationFrames /
// 59.7275, the real GB frame rate). NOT modeled (honestly, not
// silently): the auxiliary vibrato/pitch-delta stream, duty-cycle
// differences (always a plain 50% square wave here), envelope/volume
// commands, and panning -- all real, disassembled driver features this
// player does not reproduce. Good enough to prove the decode is
// correct (a real melody, not noise) -- not a faithful emulator.

const GB_FRAME_HZ = 59.7275;

function gbFreqFromPeriod(period) {
  if (period >= 2048) return null;
  const f = 131072 / (2048 - period);
  return f > 0 ? f : null;
}

class MusicPlayer {
  constructor() {
    this.ctx = null;
    this.playing = false;
    this.timeouts = [];
  }

  stop() {
    this.playing = false;
    for (const t of this.timeouts) clearTimeout(t);
    this.timeouts = [];
    if (this.ctx) {
      this.ctx.close();
      this.ctx = null;
    }
  }

  // Plays 1-3 real channel event arrays simultaneously (matching the
  // real driver's own multi-channel hardware). `onEvent(channelIndex,
  // eventIndex)` fires (scheduled via setTimeout, best-effort -- not
  // sample-accurate) as each real event starts, for UI highlighting.
  play(channelsEvents, { loop = true, onEvent = null, onStop = null } = {}) {
    this.stop();
    this.ctx = new (window.AudioContext || window.webkitAudioContext)();
    this.playing = true;
    const master = this.ctx.createGain();
    master.gain.value = 0.18; // 3 real square channels at once clips easily otherwise
    master.connect(this.ctx.destination);

    channelsEvents.forEach((events, chIdx) => {
      this._playChannel(events, master, chIdx, loop, onEvent, onStop);
    });
  }

  _playChannel(events, master, chIdx, loop, onEvent, onStop) {
    let osc = null;
    let gain = null;
    let tSeconds = 0; // real elapsed playback time, scheduled ahead via AudioContext's own clock

    const ensureOsc = () => {
      if (osc) return;
      osc = this.ctx.createOscillator();
      osc.type = "square";
      gain = this.ctx.createGain();
      gain.gain.value = 0;
      osc.connect(gain).connect(master);
      osc.start();
    };
    ensureOsc();

    const scheduleAt = (fn, seconds) => {
      const ms = Math.max(0, seconds * 1000);
      this.timeouts.push(setTimeout(() => { if (this.playing) fn(); }, ms));
    };

    for (let i = 0; i < events.length; i++) {
      const e = events[i];
      const startAt = tSeconds;
      if (e.type === "NOTE") {
        const freq = gbFreqFromPeriod(e.period);
        const durSec = (e.durationFrames || 0) / GB_FRAME_HZ;
        scheduleAt(() => {
          if (onEvent) onEvent(chIdx, i);
          if (freq && osc && gain) {
            osc.frequency.setValueAtTime(freq, this.ctx.currentTime);
            gain.gain.setValueAtTime(0.5, this.ctx.currentTime);
            gain.gain.setTargetAtTime(0.0, this.ctx.currentTime + Math.max(0.01, durSec - 0.02), 0.02);
          }
        }, startAt);
        tSeconds += durSec;
      } else if (e.type === "REST" || e.type === "NOTE_OFF") {
        const durSec = (e.durationFrames || 0) / GB_FRAME_HZ;
        scheduleAt(() => {
          if (onEvent) onEvent(chIdx, i);
          if (gain) gain.gain.setValueAtTime(0, this.ctx.currentTime);
        }, startAt);
        tSeconds += durSec;
      } else {
        // COMMAND / SET_OCTAVE / SHIFT_OCTAVE / STOP / LOOP_DETECTED / EOF --
        // real, 0-real-time driver events (see MusicDecoder.lua's own
        // doc comment: only NOTE/REST/NOTE_OFF consume real frame time).
        scheduleAt(() => { if (onEvent) onEvent(chIdx, i); }, startAt);
      }
    }

    scheduleAt(() => {
      if (loop && this.playing) {
        this._playChannel(events, master, chIdx, loop, onEvent, onStop);
      } else if (chIdx === 0 && onStop) {
        onStop();
      }
    }, tSeconds);
  }
}

function render_music(main) {
  const player = new MusicPlayer();
  onSectionUnload(() => player.stop());

  let songIndex = 0;
  let channelIndex = 1; // 1-based, matches the real song table's own channel numbering

  main.innerHTML = `
    <h1 class="page-title">Musik &amp; Sound (Bank 15)</h1>
    <p class="page-lede">
      Bis 2026-08-15 das am wenigsten untersuchte System dieses Projekts &mdash; nur der
      Treiber-Bank-Ort (15) war bekannt. Reine statische Disassemblierung (kein Live-Emulator
      nötig) fand die reale Song-Tabelle, das reale Event-Byte-Format und eine reale,
      spielbereite Frequenztabelle. <strong>Entscheidender Beweis:</strong> die Dekodierung
      erzeugt eine echte, singbare Melodie mit exakter Phrasenwiederholung &mdash; keine
      Geräusche, echte Musik. Volle Herleitung:
      <a href="https://github.com" onclick="return false;" style="pointer-events:none; color:var(--text-dim);">docs/reverse-engineering/rom-map.md</a>
      (im Hauptprojekt, Abschnitt "Audio format &mdash; DECODED").
    </p>
    <p style="color:var(--warn); font-size:13px; max-width:760px;">
      Wiedergabe ist eine echte, aber VEREINFACHTE Chiptune-Rendition: reine 50%-Rechteckwellen,
      ohne die reale Vibrato/Pitch-Delta-Zusatzschicht, Duty-Cycle-Unterschiede, Hüllkurven oder
      Panning &mdash; all das ist real disassembliert, aber hier absichtlich nicht nachgebildet
      (siehe eigener Hinweis in <code>js/viz/music.js</code>). Gut genug um zu beweisen, dass die
      Dekodierung korrekt ist &mdash; kein vollständiger Emulator.
    </p>

    <div class="toolbar">
      <select id="songSelect" aria-label="Song auswählen"></select>
      <button class="btn small" id="playBtn">▶ Abspielen (Kanal 1+2)</button>
      <button class="btn small" id="stopBtn" disabled>■ Stopp</button>
      <label style="font-size:13px; color:var(--text-dim); display:flex; align-items:center; gap:4px;">
        <input type="checkbox" id="loopCheck" checked> Loop
      </label>
    </div>

    <div class="pill-tabs" id="channelTabs" style="margin-top:10px;"></div>

    <div id="transcriptHost" style="margin-top:12px;"></div>
  `;

  const songSelect = document.getElementById("songSelect");
  for (let i = 0; i < MUSIC.songCount; i++) {
    const opt = document.createElement("option");
    opt.value = i;
    opt.textContent = `Song ${i + 1}`;
    songSelect.appendChild(opt);
  }
  songSelect.addEventListener("change", () => {
    songIndex = parseInt(songSelect.value, 10);
    player.stop();
    updatePlayStopButtons(false);
    renderTranscript();
  });

  const channelTabs = document.getElementById("channelTabs");
  [1, 2, 3].forEach(ch => {
    const tab = document.createElement("div");
    tab.className = "pill-tab" + (ch === channelIndex ? " active" : "");
    tab.textContent = "Kanal " + ch;
    tab.addEventListener("click", () => {
      channelIndex = ch;
      channelTabs.querySelectorAll(".pill-tab").forEach(t => t.classList.remove("active"));
      tab.classList.add("active");
      renderTranscript();
    });
    channelTabs.appendChild(tab);
  });

  function eventRowClass(type) {
    if (type === "NOTE") return "";
    if (type === "REST" || type === "NOTE_OFF") return "dim";
    if (type === "LOOP_DETECTED") return "verified";
    return "known-hard";
  }

  function formatEvent(e) {
    switch (e.type) {
      case "NOTE":
        return `<strong>${escapeHtml(e.noteName)}</strong> <span class="mono" style="color:var(--text-dim);">dur=${e.durationFrames}f reg=${hex(e.regPair)}</span>`;
      case "REST": return `Pause <span class="mono" style="color:var(--text-dim);">dur=${e.durationFrames}f</span>`;
      case "NOTE_OFF": return `Ton aus <span class="mono" style="color:var(--text-dim);">dur=${e.durationFrames}f</span>`;
      case "SET_OCTAVE": return `Oktave setzen &rarr; Block ${e.octaveBlock}`;
      case "SHIFT_OCTAVE": return `Oktave verschieben &rarr; ${e.signedDelta > 0 ? "+" : ""}${e.signedDelta}`;
      case "COMMAND": return `Befehl <span class="mono">${hex(e.byte, 2)}</span> ${escapeHtml(e.name || "?")}`;
      case "STOP": return "Stopp (echtes 0xFF)";
      case "LOOP_DETECTED": return "&#8635; Song wiederholt sich hier (echt, kein Fehler)";
      case "EOF": return "(Datenende erreicht)";
      default: return escapeHtml(e.type);
    }
  }

  function renderTranscript() {
    const song = MUSIC.songs[songIndex];
    const events = song.channels[channelIndex - 1];
    const host = document.getElementById("transcriptHost");
    host.innerHTML = `
      <table class="data-table">
        <thead><tr><th style="width:40px;">#</th><th>Event</th></tr></thead>
        <tbody id="eventRows"></tbody>
      </table>
    `;
    const tbody = document.getElementById("eventRows");
    events.forEach((e, i) => {
      const tr = document.createElement("tr");
      tr.id = "ev-" + channelIndex + "-" + i;
      const cls = eventRowClass(e.type);
      tr.innerHTML = `<td class="mono" style="color:var(--text-faint);">${i}</td>` +
        `<td>${cls ? `<span class="badge ${cls}" style="margin-right:6px;">${e.type}</span>` : ""}${formatEvent(e)}</td>`;
      tbody.appendChild(tr);
    });
  }

  function updatePlayStopButtons(isPlaying) {
    document.getElementById("playBtn").disabled = isPlaying;
    document.getElementById("stopBtn").disabled = !isPlaying;
  }

  document.getElementById("playBtn").addEventListener("click", () => {
    const song = MUSIC.songs[songIndex];
    const loop = document.getElementById("loopCheck").checked;
    // Real 2-channel playback (matching the real driver's own square-1
    // + square-2 hardware) -- channel 3 exists in the real data too
    // (selectable above for browsing) but is left out of simultaneous
    // playback to keep the demo's mix simple and clearly audible.
    player.play([song.channels[0], song.channels[1]], {
      loop,
      onEvent: (chIdx, evIdx) => {
        document.querySelectorAll(".ev-playing").forEach(el => el.classList.remove("ev-playing"));
        const displayedChannel = channelIndex - 1;
        if (chIdx === displayedChannel) {
          const row = document.getElementById("ev-" + channelIndex + "-" + evIdx);
          if (row) { row.classList.add("ev-playing"); row.scrollIntoView({ block: "center", behavior: "smooth" }); }
        }
      },
      onStop: () => updatePlayStopButtons(false),
    });
    updatePlayStopButtons(true);
  });

  document.getElementById("stopBtn").addEventListener("click", () => {
    player.stop();
    updatePlayStopButtons(false);
  });

  renderTranscript();
}
