-- Generates the plain, static `js/data/*.js` files the ROM Inspector
-- reads -- every number/string in those files comes directly from this
-- project's own real, already-verified Lua modules (ScriptOpcodeTable,
-- EntityStructLayout, rom_profiles, TextDecoder, ScriptRuntime) or from
-- a real, live run of the whole-corpus scan (see
-- `scripts/scan_all_scripts.lua`, same underlying method). Nothing here
-- is hand-typed ROM content -- re-run this after any future decoding
-- pass to refresh the site instead of hand-editing the generated files.
--
-- Usage (from the repo root):
--   MYSTICQUEST_ROM=/path/to/rom.gb luajit rom-inspector/tools/export_data.lua
--
-- The small amount of genuinely curated text in here (open questions,
-- "known-hard" reasons, the WRAM cell reference list) is clearly
-- separated below and cites the real docs/reverse-engineering/*.md
-- sections it's drawn from -- it does not claim to be code-derived.

package.path = "./?.lua;" .. package.path

local RomIdentity = require("src.import.RomIdentity")
local RomProfiles = require("src.import.rom_profiles")
local ScriptOpcodeTable = require("src.import.ScriptOpcodeTable")
local ScriptPointerTable = require("src.import.ScriptPointerTable")
local EntityStructLayout = require("src.import.EntityStructLayout")
local TextDecoder = require("src.import.TextDecoder")
local RomScriptStream = require("src.scripting.RomScriptStream")
local ScriptRuntime = require("src.scripting.ScriptRuntime")
local RoomFloorLayout = require("src.import.RoomFloorLayout")
local MapTable = require("src.import.MapTable")
local EnemySpeciesTable = require("src.import.EnemySpeciesTable")
local ItemTable = require("src.import.ItemTable")
local WeaponTable = require("src.import.WeaponTable")
local NpcCatalog = require("src.import.NpcCatalog")

-- Same ROM resolution convention as scripts/scan_all_scripts.lua.
local CANDIDATES = {}
CANDIDATES[#CANDIDATES + 1] = os.getenv("MYSTICQUEST_ROM")
CANDIDATES[#CANDIDATES + 1] = "baseroms/Mystic Quest (G) [!].gb"
CANDIDATES[#CANDIDATES + 1] = "../roms/extracted_mq/Mystic Quest (G) [!].gb"
CANDIDATES[#CANDIDATES + 1] = "../baseroms/Mystic Quest (G) [!].gb"
local function findRom()
  for _, path in ipairs(CANDIDATES) do
    if path then
      local f = io.open(path, "rb")
      if f then
        local data = f:read("*a")
        f:close()
        return data, path
      end
    end
  end
  return nil
end
local romData, romPath = findRom()
assert(romData, "export_data.lua: no ROM found -- set MYSTICQUEST_ROM")
io.stderr:write(string.format("using ROM: %s\n", romPath))

local report = RomIdentity.identify(romData)
local profile = RomProfiles.match(report)
assert(profile, "export_data.lua: ROM not recognized by rom_profiles.lua")

----------------------------------------------------------------------
-- Tiny Lua -> JS literal serializer (arrays vs objects auto-detected).
----------------------------------------------------------------------
local function isArray(t)
  local n = 0
  for _ in pairs(t) do n = n + 1 end
  for i = 1, n do
    if t[i] == nil then return false end
  end
  return n > 0 or next(t) == nil
end

local function jsString(s)
  return string.format("%q", s):gsub("\\\n", "\\n")
end

local function serialize(v, indent)
  indent = indent or 0
  local pad = string.rep("  ", indent)
  local pad1 = string.rep("  ", indent + 1)
  local t = type(v)
  if t == "nil" then
    return "null"
  elseif t == "boolean" then
    return tostring(v)
  elseif t == "number" then
    if v ~= v then return "null" end -- NaN guard
    return tostring(v)
  elseif t == "string" then
    return jsString(v)
  elseif t == "table" then
    if isArray(v) then
      if #v == 0 then return "[]" end
      local parts = {}
      for i = 1, #v do
        parts[#parts + 1] = pad1 .. serialize(v[i], indent + 1)
      end
      return "[\n" .. table.concat(parts, ",\n") .. "\n" .. pad .. "]"
    else
      local keys = {}
      for k in pairs(v) do keys[#keys + 1] = k end
      table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
      if #keys == 0 then return "{}" end
      local parts = {}
      for _, k in ipairs(keys) do
        parts[#parts + 1] = pad1 .. jsString(tostring(k)) .. ": " .. serialize(v[k], indent + 1)
      end
      return "{\n" .. table.concat(parts, ",\n") .. "\n" .. pad .. "}"
    end
  end
  error("serialize: unsupported type " .. t)
end

local function writeJs(filename, varName, value, headerComment)
  local outDir = "rom-inspector/js/data"
  local f = assert(io.open(outDir .. "/" .. filename, "w"))
  f:write("// AUTO-GENERATED by rom-inspector/tools/export_data.lua -- do not hand-edit.\n")
  if headerComment then
    f:write("// " .. headerComment:gsub("\n", "\n// ") .. "\n")
  end
  f:write("const " .. varName .. " = " .. serialize(value, 0) .. ";\n")
  f:close()
  io.stderr:write("wrote " .. outDir .. "/" .. filename .. "\n")
end

----------------------------------------------------------------------
-- 1. ROM basics
----------------------------------------------------------------------
writeJs("rom-basics.js", "ROM_BASICS", {
  displayName = profile.displayName,
  sha1 = profile.sha1,
  sizeBytes = profile.sizeBytes,
  cartridgeType = profile.cartridgeType,
  bankSize = profile.bankSize,
  bankCount = profile.bankCount,
}, "Real ROM identity, from RomIdentity.identify() + rom_profiles.lua's own PROFILES entry.")

----------------------------------------------------------------------
-- 2. ROM tables reference (bank/offset/status for every named table)
----------------------------------------------------------------------
local TABLE_ORDER = {
  "scriptOpcodeTable", "scriptPointerTable", "scriptOpcodeSubTable",
  "messageTextPointer", "enemySpeciesTable", "itemTable", "weaponTable",
  "noiseTable", "mapTable", "roomSelectorTable",
}
local romTables = {}
for _, key in ipairs(TABLE_ORDER) do
  local t = profile[key]
  if t then
    romTables[#romTables + 1] = {
      name = key,
      status = t.status,
      bank = t.bank,
      fileOffset = t.fileOffset,
      recordCount = t.recordCount or t.rowCount or t.length,
    }
  end
end
writeJs("rom-tables.js", "ROM_TABLES", romTables,
  "Every named, verified/partially-verified ROM table this project has located, read directly from rom_profiles.lua.")

----------------------------------------------------------------------
-- 3. Entity struct layout
----------------------------------------------------------------------
-- Curated (not code-derived, same convention this file's own header
-- comment already flags): one short, honest summary per field, drawn
-- from EntityStructLayout.lua's own dated doc comments -- so the
-- website shows the real story (including retractions), not just raw
-- offsets. Fields with no entry here simply show no note.
local FIELD_NOTES = {
  ALIVE = "0xFF = dead/empty sentinel. Setter ($0CA6) is GUARDED: once dead, a write attempt is immediately forced back to 0xFF -- no revival through this path.",
  TYPE = "RETRACTED (2026-08-14): looked attack-related from static disassembly (3 real callers write slot 4 with small integers alongside PARAM2). Live mGBA-tested across a real attack: zero value changes, and the whole code region is NEVER REACHED. The 3 static call sites are real: what they're actually for is still open.",
  PARAM2 = "The most heavily-used accessor found: 24 real getter + 17 real setter callers, spread across every ROM bank. The $C4E0 actor-command array's own slot-scan code ($4BE0, $278F) reads this field for each active $C4E0 slot's own ID byte (used as the $C200 index) and classifies its high nibble against 0x90/0xB0/0x10.",
  PARAM6 = "No standalone accessor found -- $0CBA treats offsets +6/+7 as ONE paired 16-bit value (guarded the same way as ALIVE's setter), not two independent bytes.",
  UNKNOWN_10 = "Field beyond the previously-documented 0-8 range, found 2026-08-14. Cross-confirmed via $404A (this project's own $C4E0 per-record tick handler), which reads it using the $C4E0 record's own ID byte as the $C200 slot index -- independent confirmation of that indexing convention.",
  UNKNOWN_11 = "Field beyond the previously-documented 0-8 range, found 2026-08-14. Only 1 real setter call site found (bank 0); no getter callers found in the same block.",
}
local fieldList = {}
for name, offset in pairs(EntityStructLayout.FIELD) do
  local accessor = EntityStructLayout.FIELD_ACCESSOR_ADDRESS[offset]
  fieldList[#fieldList + 1] = {
    name = name,
    offset = offset,
    accessorGet = accessor and accessor.get,
    accessorSet = accessor and accessor.set,
    note = FIELD_NOTES[name],
  }
end
table.sort(fieldList, function(a, b) return a.offset < b.offset end)
writeJs("entity-struct.js", "ENTITY_STRUCT", {
  base = EntityStructLayout.BASE,
  stride = EntityStructLayout.STRIDE,
  slotCount = EntityStructLayout.SLOT_COUNT,
  playerSlotIndex = EntityStructLayout.PLAYER_SLOT_INDEX_HYPOTHESIS,
  despawnRoutine = EntityStructLayout.DESPAWN_ROUTINE_ADDRESS,
  allocateRoutine = EntityStructLayout.ALLOCATE_ROUTINE_ADDRESS,
  pairedSetterAddress = EntityStructLayout.FIELD_ACCESSOR_ADDRESS.PAIRED_6_7_SET,
  fields = fieldList,
}, "Real, VERIFIED WRAM entity-slot struct -- see src/import/EntityStructLayout.lua's own doc comment.")

----------------------------------------------------------------------
-- 4. Opcode table: real per-opcode decode status, derived by actually
--    building a ScriptRuntime (same stub ctx as scripts/scan_all_scripts
--    .lua) and checking which handler addresses got a real registered
--    Lua implementation -- not hand-classified.
----------------------------------------------------------------------
local opcodeEntries = ScriptOpcodeTable.decode(romData, profile.scriptOpcodeTable)

-- FIXED (2026-08-15, "beende jetzt mal den full corpus scan" -- see
-- scripts/scan_all_scripts.lua's own doc comment for the full
-- rationale, duplicated here verbatim since this stub was itself an
-- independent copy carrying the exact same bug): the blanket `__index`
-- fallback below (a function always returning `true`) is only a safe
-- default for gate/predicate-shaped ctx fields. Several real fields
-- have a "return value IS the next cursor" contract instead
-- (`onFlagListExhausted`/`onTimerListExhausted09`/`0A`/
-- `onRunListExhausted0B`/`0C`, opcodes 0x08-0x0C) or a "return value is
-- an extra-byte COUNT" contract (`onControlCode`, opcode 0x04) -- the
-- generic `true` stub leaked through as a bogus non-number in both
-- cases, producing confusing "cursor true out of stream bounds" /
-- "attempt to perform arithmetic on a boolean value" errors that were
-- really scan-tool stub artifacts, not real ROM decoding gaps.
local function exhaustedListStub(opcodeLabel)
  return function(cursorAfterTerminator)
    error(string.format(
      "export_data.lua stub: opcode %s's real 'list exhausted' resume cursor " ..
      "(from real ROM cursor %#x) is genuine, data-dependent ROM content this " ..
      "scan tool has no live WRAM to derive -- not a bug in the opcode's own " ..
      "handler (see StandardScriptHandlers.zeroTerminatedFlagList's own doc comment)",
      opcodeLabel, cursorAfterTerminator))
  end
end

local stubCtx = setmetatable({
  stats = { curLP = 19, maxLP = 19, curMP = 6, maxMP = 6 },
  flags = { byte = 0 },
  wramBitFlags = { byte = 0 },
  actorStateFlags = { byte = 0 }, -- real WRAM $C4D4 shadow (opcodes 0xA3/0xA5/0xA6) --
                                    -- MUST be a real table, not the generic
                                    -- function-returning __index fallback below.
  isTriggerEventGateClear = function() return true end,
  onTimerListTest09 = function() return true end,
  onTimerListTest0A = function() return true end,
  runListMatchByte = function() return 0 end,
  isRunListGateSet = function() return true end,
  onFlagListExhausted = exhaustedListStub("0x08"),
  onTimerListExhausted09 = exhaustedListStub("0x09"),
  onTimerListExhausted0A = exhaustedListStub("0x0A"),
  onRunListExhausted0B = exhaustedListStub("0x0B"),
  onRunListExhausted0C = exhaustedListStub("0x0C"),
  onControlCode = false, -- makes StandardScriptHandlers.tick treat it as
                          -- genuinely unset (honest cursor+1/no-pin default)
                          -- instead of calling a bogus stub.
  queue = false,
}, { __index = function() return function() return true end end })
local runtime = ScriptRuntime.new(opcodeEntries, stubCtx)

-- Reverse map: real handler address -> every ScriptOpcodeTable.lua
-- constant name pointing at it (there can be several, e.g. one per
-- sibling opcode in a family) -- this is how each decoded opcode gets
-- a real, code-derived label instead of a hand-typed one.
local addressToNames = {}
for key, value in pairs(ScriptOpcodeTable) do
  if type(value) == "number" and key:match("ADDRESS") then
    addressToNames[value] = addressToNames[value] or {}
    table.insert(addressToNames[value], key)
  end
end
for _, names in pairs(addressToNames) do
  table.sort(names)
end

-- Curated (not code-derived): the small set of handler addresses this
-- project has traced but deliberately left unwired, with why -- see
-- ScriptOpcodeTable.lua's own doc comments at each address for the
-- full disassembly this summarizes.
local KNOWN_HARD = {
  -- REMOVED 2026-08-14 (task #10/"consolidate the last few hours"):
  -- 0x15A4 (opcode 0x80) used to live here ("group value is DATA-
  -- DEPENDENT... no live WRAM simulation to supply") -- that's no
  -- longer true. $02AB (the real leaf behind it) was cracked this same
  -- session (see EntityStructLayout.lua's own PLAYER_FACING_BIT doc
  -- comment and ScriptOpcodeTable.lua's ACTOR_ACTION_HANDLER_ADDRESS_80
  -- entry): it's a plain read of the player's own real facing byte,
  -- which this project DOES already track (Player.lua's `self.facing`)
  -- -- 0x80 is now a real, registered handler and correctly falls out
  -- as `status = "decoded"` below without needing this entry at all.
  --
  -- REMOVED 2026-08-15 (task #126 consolidation, "konsolidieren,
  -- dokumentieren und in die app/website einbauen"): 0x10DC (0xBC) and
  -- 0x1046 (0xBD) used to live here ("Not yet decoded to an exact fade
  -- curve" / "reads two real shared gradient lookup tables... then
  -- calls a further untraced leaf") -- both stale. `0xBC`/`0xBD`/`0xBE`
  -- (the whole palette-fade family, `$10DC`/`$1046`/`$10A7`) were fully
  -- disassembled and WIRED 2026-08-15 (`StandardScriptHandlers
  -- .paletteFadeCycle`, task #125) -- they now correctly fall out as
  -- `status = "decoded"` below without needing an entry here. Leaving
  -- the stale notes in would have been actively misleading: a
  -- "decoded" opcode showing a note that says "not yet decoded" is a
  -- real, visible self-contradiction on the website, not a harmless
  -- leftover.
  --
  -- ADDED 2026-08-15 (same consolidation pass): `0xEC`/`0xED`/`0xEE`
  -- (`$0E73`/`$0E77`/`$0E7B`) and `0xBA` (`$0EB2`) were ALREADY fully
  -- traced and deliberately left unwired back on 2026-08-14 (see
  -- `ScriptOpcodeTable.lua`'s own doc comments at each address for the
  -- complete disassembly this summarizes) but were NEVER added here --
  -- so the website was showing them as plain "undecoded" (implying
  -- genuinely open/unexplored) instead of "known-hard" (traced,
  -- deliberately deferred, with a real reason). Found and fixed while
  -- consolidating task #126 (the real `0xF3` 5-byte-release fix, which
  -- made `BossSequenceInterpreter` progress far enough to land
  -- EXACTLY on `0xED`/`$0E77` as its new honest stopping point --
  -- direct, concrete confirmation this family is real and reachable,
  -- not a hypothetical).
  [0x0E73] = "Third confirmed sibling of the known-hard $02AB family (with 0x80/0xEC/0xEE): dereferences the task-#85 cross-actor pointer ($C3FE/$C3FF) one further level (+0), then calls $02AB (a masked read of the player's own real facing byte -- itself fully understood). Left unwired because WHICH bank/pointer gets staged into $C3F0/$C3FE/$C3FF for a given real scene is genuinely DATA-DEPENDENT, and this project has no live player-entity WRAM simulation to compute it with -- expected to remain known-hard permanently, not a sign of unfinished work.",
  [0x0E77] = "Second confirmed sibling of the known-hard $02AB family (offset +1 instead of 0xEC's +0) -- same real mechanism/blocker as 0x0E73 above. Directly confirmed reachable 2026-08-15: BossSequenceInterpreter's own real boss-defeat script lands here as its new, further, honest stopping point once the 0xF3 5-byte-release fix (task #126) is wired.",
  [0x0E7B] = "Fourth confirmed sibling of the known-hard $02AB family (offset +2 instead of 0xEC's +0) -- same real mechanism/blocker as 0x0E73 above.",
  [0x0EB2] = "A real, fully-traced $D499-driven 2-step entity-lifecycle state machine (step0 allocates a real entity slot via the already-known $0A74 primitive, calls $2F03; step1 calls $2ED3 -- real halt if not ready -- else despawns the slot via $0AE3). Both $2F03/$2ED3 resolve to real cases of the already-mapped $1ED7 bank-1 dispatcher. Genuinely known-hard NOT because the mechanism is opaque (it's real, traced, decodable ROM code) but because fully resolving \"ready\" needs the $52CD sub-table's own untraced targets AND a live entity/OAM lifecycle simulation this project doesn't have.",
}

local opcodes = {}
for opcodeIndex = 0, 255 do
  local addr = opcodeEntries[opcodeIndex + 1]
  local status
  if addr == ScriptOpcodeTable.DEFAULT_HANDLER_ADDRESS then
    status = "default"
  elseif runtime.interp.handlers[addr] then
    status = "decoded"
  elseif KNOWN_HARD[addr] then
    status = "known-hard"
  else
    status = "undecoded"
  end
  local names = addressToNames[addr]
  opcodes[#opcodes + 1] = {
    opcode = opcodeIndex,
    handler = addr,
    status = status,
    names = names,
    note = KNOWN_HARD[addr],
  }
end
writeJs("opcodes.js", "OPCODES", opcodes,
  "Real per-opcode decode status for all 256 primary script opcodes -- 'decoded' means ScriptRuntime actually has a registered Lua handler for that real ROM address (checked by building a live ScriptRuntime, not hand-classified); 'default' is the real ROM-confirmed no-op; 'known-hard' is traced but deliberately unwired (see the 'note' field); 'undecoded' is genuinely open.")

----------------------------------------------------------------------
-- 4c. Opcode 0x04's own real control-code sub-system (2026-08-15,
-- tasks #141-147). These are NOT entries in the primary 256-opcode
-- table above -- they're real byte VALUES (0x10-0x1F) opcode 0x04's
-- own classifier (see StandardScriptHandlers.tick) reads directly from
-- the live script cursor while already dispatched, matching the real
-- ROM's own `$38F6` jump table (`SUB $10` before lookup). Curated, not
-- code-derived (this data doesn't live in a Lua table this project can
-- walk mechanically -- it's the direct product of live mgba tracing +
-- static disassembly, cited here exactly as found) -- see
-- docs/reverse-engineering/events.md's own dated task #141-147 entries
-- for the full real evidence trail behind every claim below.
----------------------------------------------------------------------
do
  local CONTROL_CODES = {
    {
      byte = 0x10, title = "Modus-Register setzen",
      handler = "$34E7",
      status = "occurrence-specific",
      note = "Setzt $D84A=6, dann CONDITIONAL `CALL Z,$36D0` -- die reale Bedingung ($3627, ein bank-2-Aufruf) ist nicht nachverfolgt. Live bestätigt: PINNT bei Cursor 0x61e3, PINNT NICHT bei einer früheren Vorkommnis (Cursor 0x61bc) im selben echten Durchlauf -- selbe Byte-Wert, unterschiedliches reales Verhalten.",
    },
    {
      byte = 0x11, title = "Pacing-Gate (echter $D853-Bit-7-Takt)",
      handler = "$34F4",
      status = "live-confirmed (pacing only)",
      note = "Pausiert für live bestätigte 9 echte Ticks ($D853 Bit 7), dann `CALL $36D0` unconditional. Ob das Pinnen (Rückkehr zu Opcode 0x04) für JEDE reale Vorkommnis gilt, ist NICHT bestätigt -- ein erster Versuch, das anzunehmen, brach eine andere, bereits funktionierende echte HEAL_LP-Dispatch -- zurückgesetzt auf den ehrlichen Standard (kein Pin).",
    },
    {
      byte = 0x12, title = "Bank-2-Bedingung -> 0xFF Sub-Opcode 4",
      handler = "$3502 -> $350F",
      status = "occurrence-specific (156 echte Ticks)",
      note = "Bedingt (`$1ED1`, ein realer Bank-2-Funktionsaufruf-Trampolin) Brücke in 0xFF Sub-Opcode 4. Live-getraced: genau 156 echte Ticks Pause für DIESE Vorkommnis (Cursor 0x6206), dann unconditional Rückkehr zu Opcode 0x04 via $36D0. Bank 2s eigene interne Berechnung nicht nachverfolgt (bewusst zurückgestellt, wie bei anderen $1F06-Aufrufen dieses Projekts).",
    },
    {
      byte = 0x14, title = "Namenseinfügung -> 0xFF Sub-Opcode 1",
      handler = "$357D",
      status = "occurrence-specific (1 echter Tick)",
      note = "Brücke in 0xFF Sub-Opcode 1 für GENAU EINEN echten Tick ($D85A kurzzeitig =0xFF, live bestätigt), dann Rückkehr zu Opcode 0x04 zwei echte Bytes weiter. Die echte Namenseinfügung selbst (Heldenname) wird NICHT modelliert -- nur die korrekte Cursor-Fortsetzung.",
    },
    {
      byte = 0x1a, title = "NEWLINE_BYTE (Zeilenumbruch)",
      handler = "$35B0",
      status = "generalisiert, sicher",
      note = "UNCONDITIONAL `CALL $36D0` (kein Gate, anders als 0x10) -- vollständige Disassemblierung bestätigt: sicher für JEDE reale Vorkommnis zu verallgemeinern. Bereits unabhängig durch TextDecoder.lua's eigene, komplett getrennte Reverse-Engineering bestätigt (echte Kreuzvalidierung).",
    },
    {
      byte = 0x1b, title = "Cursor-Setup -> 0xFF Sub-Opcode 2",
      handler = "$35C1 -> $3648",
      status = "occurrence-specific (1 echter Tick)",
      note = "Setzt reale $D8B2-$D8B5 Cursor-Position-Zellen, dann Brücke in 0xFF Sub-Opcode 2 für GENAU EINEN echten Tick (live bestätigt), dann Rückkehr zu Opcode 0x04. $3648 enthält selbst eine reale Bedingung ($D84A==0?) für einen weiteren, nicht verfolgten Pfad -- daher nur für DIESE Vorkommnis (Cursor 0x6207) übernommen, nicht verallgemeinert.",
    },
  }
  writeJs("control-codes.js", "CONTROL_CODES", CONTROL_CODES,
    "Real control-code sub-system opcode 0x04's own classifier dispatches through (script byte values 0x10-0x1F, NOT separate top-level opcodes -- see StandardScriptHandlers.tick's own doc comment). Found and fixed 2026-08-15 (tasks #141-147) via live mgba tracing + static disassembly -- 'occurrence-specific' means this project only claims the real behavior for the ONE live-traced real cursor cited, NOT every occurrence of that byte value (two self-caught over-generalizations this session -- 0x10 and 0x11 -- both broke real, already-working dispatches when assumed universal). With all confirmed here wired, this project's own BossSequenceInterpreter now runs the ENTIRE remaining real boss-defeat script and reaches the real opcode 0x00 queue-gate (see docs/reverse-engineering/events.md) -- the same landmark this whole investigation started from.")
end

----------------------------------------------------------------------
-- 4b. Script-tracer EXAMPLES (2026-08-14, direct user request: "kannst
--     du mal den ganzen script mechanismus mal in app... intuitiver
--     darstellen. vielleicht mit einem beispielscript so das man
--     verfolgen kann was passiert"). Two real, already-decoded, SHORT
--     event scripts from the room catalog (`MapTable.tryDecodeActor
--     Action`'s own real examples this session) -- small enough to
--     walk through opcode-by-opcode without needing to port this
--     project's whole ScriptRuntime to JS. Only real FILE OFFSETS are
--     exported (never raw ROM bytes, same "never ship ROM content"
--     convention every other page here already follows) -- the
--     client reads and decodes live from the user's own locally
--     loaded ROM file.
----------------------------------------------------------------------
local function headerFileOffsetFor(mapTable, recordIndex)
  local records = MapTable.decode(romData, mapTable)
  local record = records[recordIndex + 1]
  local headerAddr = record.headerAddr
  return mapTable.bankFileStart + (headerAddr - 0x4000)
end
local scriptExamples = {
  {
    id = "actor-action",
    title = "Bank-5-Raum 0: ein Actor-Action-Ereignis-Skript",
    scriptFileOffset = headerFileOffsetFor(profile.mapTable, 0),
    -- Real, already-verified this session (see MapTable.lua's own
    -- "NAMING CORRECTED" doc comment + events.md's dated writeup):
    -- opcode $76 resolves to handler $152C, matching the ALREADY-
    -- documented ACTOR_ACTION family shape byte for byte.
  },
  {
    id = "default-fallthrough",
    title = "Bank-5-Raum 1: ein Opcode ist No-Op, das Skript geht zum nächsten Byte weiter",
    scriptFileOffset = headerFileOffsetFor(profile.mapTable, 1),
    -- Real: opcode $7C resolves to the ROM-confirmed DEFAULT_HANDLER
    -- (a genuine no-op) -- the interpreter does NOT stop, it reads the
    -- next byte ($00) as the next real opcode, which resolves to the
    -- ALREADY fully-decoded QUEUE_GATE_HANDLER_ADDRESS ($3297, opcode
    -- 0x00 -- a real conditional halt on the script continuation
    -- queue, this project's own already-implemented mechanism). A
    -- complete, well-understood 2-opcode chain, not an open ending.
  },
}
writeJs("script-example.js", "SCRIPT_EXAMPLES", scriptExamples,
  "2 real, curated example event scripts for the Skript-Opcode-Explorer's own interactive step-tracer -- only real ROM file offsets, decoded live client-side from the user's own loaded ROM (never shipped ROM bytes). See MapTable.lua's own 'NAMING CORRECTED' doc comment and events.md's dated writeup for the full evidence these bytes really are script bytecode.")

----------------------------------------------------------------------
-- 5. Whole-corpus scan results (same method as scripts/scan_all_scripts.lua)
----------------------------------------------------------------------
local spt = profile.scriptPointerTable
local FILLER, CLEAN, HALT_UNDECODED, ERROR_OTHER = "filler", "clean", "halt_undecoded", "error_other"
local haltCounts = {}
local statusCounts = { [FILLER] = 0, [CLEAN] = 0, [HALT_UNDECODED] = 0, [ERROR_OTHER] = 0 }
local stepBudget = 500
for index = 0, spt.recordCount - 1 do
  local resolved = ScriptPointerTable.resolve(romData, spt, index)
  if not resolved then
    statusCounts[FILLER] = statusCounts[FILLER] + 1
  else
    local stream = RomScriptStream.forFileOffset(romData, resolved.bank * 0x4000)
    local shadowRuntime = ScriptRuntime.new(opcodeEntries, stubCtx)
    local ok, err = pcall(function()
      shadowRuntime:run(stream, resolved.cpuAddress, stepBudget)
    end)
    if not ok then
      statusCounts[ERROR_OTHER] = statusCounts[ERROR_OTHER] + 1
    elseif shadowRuntime.stopped then
      local addrHex = tostring(shadowRuntime.stopError):match("real ROM handler (0x%x+)")
      if addrHex then
        statusCounts[HALT_UNDECODED] = statusCounts[HALT_UNDECODED] + 1
        haltCounts[addrHex] = (haltCounts[addrHex] or 0) + 1
      else
        statusCounts[ERROR_OTHER] = statusCounts[ERROR_OTHER] + 1
      end
    else
      statusCounts[CLEAN] = statusCounts[CLEAN] + 1
    end
  end
end
local haltList = {}
for addrHex, count in pairs(haltCounts) do
  local addrNum = tonumber(addrHex)
  haltList[#haltList + 1] = { address = addrHex, count = count, names = addressToNames[addrNum], note = KNOWN_HARD[addrNum] }
end
table.sort(haltList, function(a, b) return a.count > b.count end)
local top = {}
for i = 1, math.min(30, #haltList) do top[i] = haltList[i] end
writeJs("scan-results.js", "SCAN_RESULTS", {
  totalScripts = spt.recordCount,
  stepBudget = stepBudget,
  clean = statusCounts[CLEAN],
  haltUndecoded = statusCounts[HALT_UNDECODED],
  errorOther = statusCounts[ERROR_OTHER],
  filler = statusCounts[FILLER],
  topBlockers = top,
}, "Real, live whole-corpus shadow-run result -- every real scriptPointerTable entry (all 1357), run through the CURRENT opcode coverage. Same method as scripts/scan_all_scripts.lua.")

----------------------------------------------------------------------
-- 6. Room graph
----------------------------------------------------------------------
local rooms = {}
for name, room in pairs(profile.graphics) do
  if type(room) == "table" and room.exits then
    local exits = {}
    for _, exit in ipairs(room.exits) do
      exits[#exits + 1] = {
        status = exit.status,
        targetRoom = exit.targetRoom,
        transitionType = exit.transition and exit.transition.type,
        axis = exit.transition and exit.transition.axis,
        totalPixels = exit.transition and exit.transition.totalPixels,
        reverse = exit.transition and exit.transition.reverse or false,
      }
    end
    local widthTiles, heightTiles
    if room.grid then
      heightTiles = #room.grid
      widthTiles = room.grid[1] and #room.grid[1]
    end
    rooms[#rooms + 1] = { name = name, widthTiles = widthTiles, heightTiles = heightTiles, exits = exits }
  end
end
table.sort(rooms, function(a, b) return a.name < b.name end)
writeJs("rooms.js", "ROOMS", rooms,
  "Every room with real, decoded exits -- read directly from rom_profiles.lua's own graphics.<room>.exits (empirically-found trigger zones + transition shape + target room).")

----------------------------------------------------------------------
-- 6b. Room MAPS (grid + tileOffsets) -- for the Tile/Map viewers. Only
--     the real tile IDS/offsets/grid are exported here; the actual
--     16-byte tile PIXEL data is never embedded -- the viewer decodes
--     it live from a ROM file the user supplies locally in their own
--     browser (this project never ships ROM bytes, same convention as
--     RomLocator.lua elsewhere in the main codebase).
----------------------------------------------------------------------
local roomMaps = {}
for name, room in pairs(profile.graphics) do
  if type(room) == "table" and room.grid and room.tileOffsets then
    local tileOffsets = {}
    for tileId, off in pairs(room.tileOffsets) do
      if type(off) == "string" then
        -- A handful of real tiles are stored as a literal 16-byte
        -- pattern rather than a ROM file offset (e.g. fourthRoom/
        -- sixthRoom's own tile 128, a real known-solid tile with no
        -- single canonical ROM address) -- exported as the raw byte
        -- VALUES so the viewer can render it without needing a ROM
        -- offset to dereference.
        assert(#off == 16, "export_data.lua: literal tile pattern must be exactly 16 bytes")
        local bytes = {}
        for i = 1, 16 do bytes[i] = off:byte(i) end
        tileOffsets[tostring(tileId)] = { literal = bytes }
      else
        tileOffsets[tostring(tileId)] = off
      end
    end
    roomMaps[#roomMaps + 1] = {
      name = name,
      cols = room.grid[1] and #room.grid[1] or 0,
      rows = #room.grid,
      grid = room.grid,
      tileOffsets = tileOffsets,
      floorTileIds = room.floorTileIds,
    }
  end
end
table.sort(roomMaps, function(a, b) return a.name < b.name end)
writeJs("room-maps.js", "ROOM_MAPS", roomMaps,
  "Every real, decoded room/screen tilemap (grid of tile IDs + tile ID -> ROM file offset lookup) -- read directly from rom_profiles.lua's own graphics.<name>.grid/tileOffsets. No tile PIXEL data is embedded -- the Tile/Map viewer pages decode it live from a user-supplied ROM file, entirely client-side.")

----------------------------------------------------------------------
-- 6c. Room CATALOG -- ALL 320 real, individually-decodable bank-5/
--     bank-6 map-table records (2026-08-14, "andere räume, so viele
--     wie möglich, raumdaten reicht"), not just the 8 rooms real
--     gameplay actually reaches. Reuses the EXACT SAME already-tested
--     pipeline `src/app/states/RoomExplorer.lua`'s dev-only F8 browser
--     already drives live in the LÖVE app
--     (`RoomFloorLayout.buildRoomFromMapTableRecord` +
--     `toTileGridBackgroundData`) -- no new discovery here, just
--     exporting an already-verified capability as static site data so
--     it's browsable without a live LÖVE session.
--
--     HONEST SCOPE, UPGRADED 2026-08-14 ("gehe dem map header hinweis
--     nach"): all 320 records now render through `genericCatalogMeta
--     tileTableFileOffset` -- a real, structurally-justified DEFAULT
--     table, not the `unknownRoomACandidates`-borrowed placeholder
--     this export used before. Derivation: `roomSelectorTable`'s own
--     record 0/1 (bank5's and bank6's own "map", VERIFIED via
--     `RoomSelectorTable.resolveMapRoomPointersFileOffset`'s exact
--     byte match to each table's real header) share one real
--     `tileSourcePointer`, cross-checked against the external
--     FFA-Disassembly project's own documented "one tileset per map,
--     no per-room override" US-ROM architecture. Real, but NOT
--     independently ground-truth-verified -- no live gameplay reaches
--     any of these 320 rooms. See rom_profiles.lua's own dated
--     "UPGRADED" doc comments and rom-map.md's "World scope" sections
--     for the full evidence chain, including 2 negative methods tried
--     and ruled out before this one was found.
--
--     `actorAction` field ADDED 2026-08-14 ("verfolge mal diese
--     eventscripte und schaue dir an was diese machen"): each
--     record's own real "header" bytes are now understood to be a
--     genuine per-room EVENT SCRIPT (see MapTable.lua's own "NAMING
--     CORRECTED" doc comment) -- `MapTable.tryDecodeActorAction`
--     extracts the real, already-documented `(group, action)` pair
--     when a record's script matches the ALREADY-KNOWN "ACTOR_ACTION"
--     opcode family (`ScriptOpcodeTable.lua`'s own `ACTOR_ACTION_
--     HANDLER_ADDRESS_*` constants -- a real actor-command-queue
--     mechanism, `$C4E0`/`$C5A0`, per that module's own corrected
--     note -- NOT room-selection, spawn-coordinate, or TILE data).
--     `nil` for the majority of records whose own script doesn't
--     match this specific family (a real, honest "not this family"
--     result, not every room necessarily using it).
----------------------------------------------------------------------
local roomCatalog = {}
local catalogMetatileTableFileOffset =
  profile.roomFloorLayoutPipeline.genericCatalogMetatileTableFileOffset
local function exportCatalogSource(mapTable, sourceLabel)
  local opts = {
    metatileTableFileOffset = catalogMetatileTableFileOffset,
    tilesetFileOffset = mapTable.tilesetFileOffset,
    metatileGridRows = 8,
    metatileGridCols = 10,
  }
  local records = MapTable.decode(romData, mapTable)
  for recordIndex = 0, mapTable.recordCount - 1 do
    local fileOffsetGrid = RoomFloorLayout.buildRoomFromMapTableRecord(romData, mapTable, recordIndex, opts)
    local room = RoomFloorLayout.toTileGridBackgroundData(fileOffsetGrid, opts.tilesetFileOffset)
    local tileOffsets = {}
    for tileId, off in pairs(room.tileOffsets) do
      tileOffsets[tostring(tileId)] = off
    end
    local record = records[recordIndex + 1]
    local actorAction = record and record.header and
      MapTable.tryDecodeActorAction(romData, record.header, opcodeEntries)
    roomCatalog[#roomCatalog + 1] = {
      name = string.format("%s-record-%03d", sourceLabel, recordIndex),
      source = sourceLabel,
      recordIndex = recordIndex,
      cols = room.grid[1] and #room.grid[1] or 0,
      rows = #room.grid,
      grid = room.grid,
      tileOffsets = tileOffsets,
      actorAction = actorAction, -- {group=N, action=N} or nil, see doc comment above
    }
  end
end
exportCatalogSource(profile.mapTable, "bank5")
exportCatalogSource(profile.mapTableBank6, "bank6")
-- bank7 ADDED 2026-08-14 ("weiter bohren bis es fertig ist"): the
-- Templated (mode 1) encoding is now CRACKED end to end (base-room RLE
-- template + per-record (value,position) diff, see MapTable.lua's own
-- `readTemplatedHeader`/`applyTemplatedDiff` and rom-map.md's "bank 7
-- Templated revisited, CRACKED"). Exercised through the EXACT SAME
-- `exportCatalogSource` helper as bank5/6 -- `RoomFloorLayout.build
-- RoomFromMapTableRecord` dispatches on the map's own real header
-- `encodingMode` internally, so this call site needed no changes.
exportCatalogSource(profile.mapTableBank7, "bank7")
writeJs("room-catalog.js", "ROOM_CATALOG", roomCatalog,
  "ALL 384 real, individually-decodable bank-5 (256 RLE records) + bank-6 (64 RLE records) + bank-7 (64 Templated records, CRACKED 2026-08-14) map-table entries -- the same general pipeline RoomExplorer.lua's dev-only F8 browser already drives live in the LÖVE app, exported here as static data. UPGRADED 2026-08-14: every entry now renders through genericCatalogMetatileTableFileOffset, a real, structurally-derived default (roomSelectorTable's own record 0/1, cross-checked against the external FFA-Disassembly project's documented 'one tileset per map' architecture) -- not the unverified unknownRoomA-borrowed placeholder used before. Still NOT independently ground-truth-verified (no live gameplay reaches these 384 rooms). bank7's own real per-record diff format (base template + (value,position) overrides) is separately VERIFIED against all 64 records (566/566 valid diff positions, tile_entropy 1.30-1.40 bits for all 64, zero outliers) -- see rom_profiles.lua's own `mapTableBank7` doc comment. `actorAction` (added 2026-08-14): the real (group,action) pair a record's own per-room event script enqueues, when it matches the already-documented ACTOR_ACTION opcode family -- a real actor-command-queue mechanism, NOT tile/graphics data. See rom_profiles.lua's own dated doc comments and rom-map.md's 'World scope' sections for the full evidence chain.")

writeJs("font-tileset.js", "FONT_TILESET", {
  fileOffset = profile.graphics.font.fileOffset,
  bank = profile.graphics.font.bank,
  tileCount = profile.graphics.font.tileCount,
  rowGlyphs = profile.graphics.font.rowGlyphs,
}, "The real, VERIFIED font tileset location -- rom_profiles.lua's own graphics.font.")

----------------------------------------------------------------------
-- 7. Text decoder tables
----------------------------------------------------------------------
local umlauts = {}
for byte, ch in pairs(TextDecoder.UMLAUT_PARTIAL) do
  umlauts[#umlauts + 1] = { byte = byte, char = ch }
end
table.sort(umlauts, function(a, b) return a.byte < b.byte end)
local digraphs = {}
for byte, pair in pairs(TextDecoder.DIGRAPH_PARTIAL) do
  digraphs[#digraphs + 1] = { byte = byte, chars = pair }
end
table.sort(digraphs, function(a, b) return a.byte < b.byte end)

-- Real byte samples straight from the ROM (not hand-typed) -- read
-- until a real TERMINATOR_BYTE (or 40 bytes, as a safety cap) starting
-- at each already-VERIFIED real text file offset.
local function readRealSample(fileOffset, label)
  local bytes = {}
  local i = fileOffset
  while i < #romData and #bytes < 40 do
    local b = romData:byte(i + 1)
    bytes[#bytes + 1] = b
    if b == TextDecoder.TERMINATOR_BYTE then break end
    i = i + 1
  end
  local decoded = TextDecoder.decodeString(romData, fileOffset)
  return { label = label, fileOffset = fileOffset, bytes = bytes, decoded = decoded }
end
local textSamples = {
  readRealSample(profile.messageTextPointer.verifiedExample.textFileOffset,
    "messageID 13 (\"gefunden\" item-pickup text)"),
  readRealSample(0x3A268, "the real dump this project's digraph table was built from (starts on a literal \"WILLY\")"),
  readRealSample(profile.graphics.introText.fileOffset, "intro scroll text"),
}

writeJs("text-decoder.js", "TEXT_DECODER", {
  samples = textSamples,
  mainGlyphs = TextDecoder.MAIN_GLYPHS,
  mainBase = TextDecoder.MAIN_BASE,
  spaceByte = TextDecoder.SPACE_BYTE,
  terminatorByte = TextDecoder.TERMINATOR_BYTE,
  periodByte = TextDecoder.PERIOD_BYTE,
  hyphenByte = TextDecoder.HYPHEN_BYTE,
  newlineByte = TextDecoder.NEWLINE_BYTE,
  exclamationByte = TextDecoder.EXCLAMATION_BYTE,
  questionByte = TextDecoder.QUESTION_BYTE,
  colonByte = TextDecoder.COLON_BYTE,
  umlauts = umlauts,
  digraphs = digraphs,
}, "Real TextDecoder.lua tables -- see that file's own doc comment for how each byte was cross-checked against live-decoded ROM text.")

----------------------------------------------------------------------
-- 11. Monster catalog (EnemySpeciesTable -- 11 real species, ATK
-- VERIFIED, defCandidate1/2 real but not confirmed as a consumed
-- stat -- see combat.md's dated 2026-08-15 entries). Only ONE species
-- has a known real sprite location (the tutorial "gate creature");
-- the rest are honestly flagged as "graphic unknown", not guessed.
----------------------------------------------------------------------
local function bytesToArray(raw)
  local out = {}
  for i = 1, #raw do out[i] = raw:byte(i) end
  return out
end

do
  local rows = EnemySpeciesTable.decode(romData, profile.enemySpeciesTable)
  local species = EnemySpeciesTable.groupBySpecies(rows)
  local monsters = {}
  local KNOWN_SPRITE_ROW = profile.enemySpeciesTable.verifiedExample
    and profile.enemySpeciesTable.verifiedExample.rowIndex
  for i, s in ipairs(species) do
    monsters[i] = {
      speciesIndex = i - 1,
      firstRowIndex = s.firstRowIndex,
      rowCount = s.count,
      flagVariant = s.row.flagVariant,
      atk = s.row.atk,
      defCandidate1 = s.row.defCandidate1,
      defCandidate2 = s.row.defCandidate2,
      rawBytes = bytesToArray(s.row.raw),
      -- true only for the one species this project has actually
      -- fought and captured a real live sprite location for (see
      -- rom_profiles.lua's own `enemySprite` field) -- every other
      -- species honestly has no known graphic yet.
      knownSprite = (KNOWN_SPRITE_ROW ~= nil) and (s.firstRowIndex - 1 <= KNOWN_SPRITE_ROW)
        and (KNOWN_SPRITE_ROW < s.firstRowIndex - 1 + s.count) or false,
    }
  end
  local es = profile.graphics and profile.graphics.enemySprite
  writeJs("monsters.js", "MONSTERS", {
    species = monsters,
    knownSprite = es and {
      tileOffsets = es.tileOffsets,
      cols = es.cols,
      rows = es.rows,
      screenX = es.screenX,
      screenY = es.screenY,
      -- ADDED 2026-08-15 (direct follow-up, "sprites mit
      -- animationsphasen"): the real hardware X-flip toggle IS this
      -- creature's own real 2nd animation "frame" (a horizontal
      -- mirror of the SAME tiles, not a second drawn frame -- see
      -- rom_profiles.lua's own `enemySprite.flipXTogglesPerStep` doc
      -- comment for the full live OAM trace). Exposed explicitly so
      -- the website/CatalogExplorer can show BOTH real poses instead
      -- of just the un-flipped one.
      flipXTogglesPerStep = es.flipXTogglesPerStep or false,
    } or nil,
  }, "Real enemySpeciesTable rows (EnemySpeciesTable.lua), grouped into 11 distinct species. " ..
     "ATK is VERIFIED (live register match); defCandidate1/2 are real bytes with NO confirmed " ..
     "consumer found after 4 independent leads (see combat.md's 2026-08-15 entries) -- shown " ..
     "as raw data, not claimed to be a working DEF stat. Only 1 of 11 species has a known real " ..
     "sprite (found via live OAM tracing during actual combat) -- honestly flagged per-species; " ..
     "that one real sprite's own 2-pose animation (X-flip toggle) is included under knownSprite.")
end

----------------------------------------------------------------------
-- 12. Item/spell + weapon/armor catalog (ItemTable.lua/WeaponTable.lua
-- -- both table boundaries substantially extended 2026-08-15, see
-- rom_profiles.lua's own dated doc comments).
----------------------------------------------------------------------
do
  local itemRecords = ItemTable.decode(romData, profile.itemTable)
  local items = {}
  for i, r in ipairs(itemRecords) do
    items[i] = {
      index = r.index,
      name = r.name,
      categoryByte = r.categoryByte,
      id = r.id,
      namePrefixByte = r.namePrefixByte,
      isSpell = r.index >= profile.itemTable.categoryBoundaryRecord,
    }
  end

  local weaponRecords = WeaponTable.decode(romData, profile.weaponTable)
  local weapons = {}
  for i, r in ipairs(weaponRecords) do
    weapons[i] = {
      index = r.index,
      name = r.name,
      categoryByte = r.categoryByte,
      statBytes = bytesToArray(r.statBytes),
    }
  end

  -- Catalog plan Phase 2 (2026-08-15, direct user request "Items in
  -- mehr auswählbare Kategorien unterteilen"): real categoryByte
  -- groupings, for the website's category filter pills -- see
  -- ItemTable.lua's/WeaponTable.lua's own `groupByCategory` doc
  -- comments for exactly what `sizeClass` does and does not claim.
  -- Only the summary (categoryByte/count/sizeClass) is exported here,
  -- not the nested record lists -- the flat `items`/`weapons` arrays
  -- above already carry the full records, and each row's own
  -- `categoryByte` is enough for the website to filter client-side
  -- without duplicating the data.
  local itemCategories = {}
  for i, g in ipairs(ItemTable.groupByCategory(itemRecords)) do
    itemCategories[i] = { categoryByte = g.categoryByte, count = g.count, sizeClass = g.sizeClass }
  end
  local weaponCategories = {}
  for i, g in ipairs(WeaponTable.groupByCategory(weaponRecords)) do
    weaponCategories[i] = { categoryByte = g.categoryByte, count = g.count, sizeClass = g.sizeClass }
  end

  writeJs("items.js", "ITEMS", {
    items = items,
    weapons = weapons,
    categoryBoundaryRecord = profile.itemTable.categoryBoundaryRecord,
    itemCategories = itemCategories,
    weaponCategories = weaponCategories,
  }, "Real item/spell table (ItemTable.lua) and weapon/armor table (WeaponTable.lua). Names " ..
     "decode cleanly for most records (2026-08-15: found spell records need a 2nd real name " ..
     "offset, see ItemTable.lua's own doc comment) -- records with name=\"\" genuinely don't " ..
     "decode at either known offset, shown honestly rather than guessed. Stat bytes beyond the " ..
     "name are real but NOT interpreted (raw only). itemCategories/weaponCategories (2026-08-15, " ..
     "catalog plan Phase 2) group the real records by their real categoryByte -- sizeClass is a " ..
     "plain size threshold (>=5 records), NOT a claimed real slot name (e.g. weapon/armor/helm) -- " ..
     "see WeaponTable.lua's own doc comment for why that's still unconfirmed.")
end

----------------------------------------------------------------------
-- 13. NPC catalog (NpcCatalog.lua) -- NOT a static ROM table (see that
-- module's own doc comment for why "complete" here means "every NPC
-- this project has actually found," not "every NPC in the ROM").
----------------------------------------------------------------------
writeJs("npcs.js", "NPCS", NpcCatalog.build(profile),
  "Real NPCs this project has found and placed, read from rom_profiles.lua's own verified " ..
  "scene data (NpcCatalog.lua). No static ROM table backs NPC placement in this game -- each " ..
  "entry was found individually via live OAM tracing + per-room dialogue testing, not decoded " ..
  "from a table this exporter could walk mechanically.")

----------------------------------------------------------------------
-- 14. Story text census (rom_profiles.lua's new `storyText`, 2026-08-15,
-- direct user request "suchen alle monster und npcs mit allen daten,
-- texten und grafiken aus dem rom") -- real monster defeat messages
-- and named story characters, found via tools/rom/dump_strings.py's
-- already-proven text scanner (the same method that found Amanda's
-- own real secondRoom dialogue), NOT decoded from a table -- see
-- rom_profiles.lua's own doc comment for the full honesty scope.
----------------------------------------------------------------------
if profile.storyText then
  writeJs("story.js", "STORY", profile.storyText,
    "Real ROM-wide text census: monster \"<Name> bezwungen/besiegt\" victory messages and " ..
    "named story characters, found via a targeted tools/rom/dump_strings.py scan. Only Willy " ..
    "and Amanda have a known live room/sprite (positionKnown=true) -- every other name was " ..
    "found in dialogue text only, with NO live position ever captured for it " ..
    "(positionKnown=false, honestly labeled, not omitted). bossDefeats has NO confirmed link " ..
    "to enemySpeciesTable's own 11 numbered species rows -- shown standalone, not force-matched.")
end

io.stderr:write("done.\n")
