-- Generates the plain, static `js/data/*.js` files the ROM Inspector
-- reads -- every number/string in those files comes directly from this
-- project's own real, already-verified Lua modules (ScriptOpcodeTable,
-- EntityStructLayout, rom_profiles, TextDecoder, ScriptRuntime) or from
-- a real, live run of the whole-corpus scan (see
-- `scripts/scan_all_scripts.lua`, same underlying method). Nothing here
-- is hand-typed ROM content -- re-run this after any future decoding
-- pass to refresh the site instead of hand-editing the generated files.
--
-- Usage (from the repo root):
--   MYSTICQUEST_ROM=/path/to/rom.gb luajit rom-inspector/tools/export_data.lua
--
-- The small amount of genuinely curated text in here (open questions,
-- "known-hard" reasons, the WRAM cell reference list) is clearly
-- separated below and cites the real docs/reverse-engineering/*.md
-- sections it's drawn from -- it does not claim to be code-derived.

package.path = "./?.lua;" .. package.path

local RomIdentity = require("src.import.RomIdentity")
local RomProfiles = require("src.import.rom_profiles")
local ScriptOpcodeTable = require("src.import.ScriptOpcodeTable")
local ScriptPointerTable = require("src.import.ScriptPointerTable")
local EntityStructLayout = require("src.import.EntityStructLayout")
local TextDecoder = require("src.import.TextDecoder")
local RomScriptStream = require("src.scripting.RomScriptStream")
local ScriptRuntime = require("src.scripting.ScriptRuntime")
local RoomFloorLayout = require("src.import.RoomFloorLayout")
local MapTable = require("src.import.MapTable")

-- Same ROM resolution convention as scripts/scan_all_scripts.lua.
local CANDIDATES = {}
CANDIDATES[#CANDIDATES + 1] = os.getenv("MYSTICQUEST_ROM")
CANDIDATES[#CANDIDATES + 1] = "baseroms/Mystic Quest (G) [!].gb"
CANDIDATES[#CANDIDATES + 1] = "../roms/extracted_mq/Mystic Quest (G) [!].gb"
CANDIDATES[#CANDIDATES + 1] = "../baseroms/Mystic Quest (G) [!].gb"
local function findRom()
  for _, path in ipairs(CANDIDATES) do
    if path then
      local f = io.open(path, "rb")
      if f then
        local data = f:read("*a")
        f:close()
        return data, path
      end
    end
  end
  return nil
end
local romData, romPath = findRom()
assert(romData, "export_data.lua: no ROM found -- set MYSTICQUEST_ROM")
io.stderr:write(string.format("using ROM: %s\n", romPath))

local report = RomIdentity.identify(romData)
local profile = RomProfiles.match(report)
assert(profile, "export_data.lua: ROM not recognized by rom_profiles.lua")

----------------------------------------------------------------------
-- Tiny Lua -> JS literal serializer (arrays vs objects auto-detected).
----------------------------------------------------------------------
local function isArray(t)
  local n = 0
  for _ in pairs(t) do n = n + 1 end
  for i = 1, n do
    if t[i] == nil then return false end
  end
  return n > 0 or next(t) == nil
end

local function jsString(s)
  return string.format("%q", s):gsub("\\\n", "\\n")
end

local function serialize(v, indent)
  indent = indent or 0
  local pad = string.rep("  ", indent)
  local pad1 = string.rep("  ", indent + 1)
  local t = type(v)
  if t == "nil" then
    return "null"
  elseif t == "boolean" then
    return tostring(v)
  elseif t == "number" then
    if v ~= v then return "null" end -- NaN guard
    return tostring(v)
  elseif t == "string" then
    return jsString(v)
  elseif t == "table" then
    if isArray(v) then
      if #v == 0 then return "[]" end
      local parts = {}
      for i = 1, #v do
        parts[#parts + 1] = pad1 .. serialize(v[i], indent + 1)
      end
      return "[\n" .. table.concat(parts, ",\n") .. "\n" .. pad .. "]"
    else
      local keys = {}
      for k in pairs(v) do keys[#keys + 1] = k end
      table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
      if #keys == 0 then return "{}" end
      local parts = {}
      for _, k in ipairs(keys) do
        parts[#parts + 1] = pad1 .. jsString(tostring(k)) .. ": " .. serialize(v[k], indent + 1)
      end
      return "{\n" .. table.concat(parts, ",\n") .. "\n" .. pad .. "}"
    end
  end
  error("serialize: unsupported type " .. t)
end

local function writeJs(filename, varName, value, headerComment)
  local outDir = "rom-inspector/js/data"
  local f = assert(io.open(outDir .. "/" .. filename, "w"))
  f:write("// AUTO-GENERATED by rom-inspector/tools/export_data.lua -- do not hand-edit.\n")
  if headerComment then
    f:write("// " .. headerComment:gsub("\n", "\n// ") .. "\n")
  end
  f:write("const " .. varName .. " = " .. serialize(value, 0) .. ";\n")
  f:close()
  io.stderr:write("wrote " .. outDir .. "/" .. filename .. "\n")
end

----------------------------------------------------------------------
-- 1. ROM basics
----------------------------------------------------------------------
writeJs("rom-basics.js", "ROM_BASICS", {
  displayName = profile.displayName,
  sha1 = profile.sha1,
  sizeBytes = profile.sizeBytes,
  cartridgeType = profile.cartridgeType,
  bankSize = profile.bankSize,
  bankCount = profile.bankCount,
}, "Real ROM identity, from RomIdentity.identify() + rom_profiles.lua's own PROFILES entry.")

----------------------------------------------------------------------
-- 2. ROM tables reference (bank/offset/status for every named table)
----------------------------------------------------------------------
local TABLE_ORDER = {
  "scriptOpcodeTable", "scriptPointerTable", "scriptOpcodeSubTable",
  "messageTextPointer", "enemySpeciesTable", "itemTable", "weaponTable",
  "noiseTable", "mapTable", "roomSelectorTable",
}
local romTables = {}
for _, key in ipairs(TABLE_ORDER) do
  local t = profile[key]
  if t then
    romTables[#romTables + 1] = {
      name = key,
      status = t.status,
      bank = t.bank,
      fileOffset = t.fileOffset,
      recordCount = t.recordCount or t.rowCount or t.length,
    }
  end
end
writeJs("rom-tables.js", "ROM_TABLES", romTables,
  "Every named, verified/partially-verified ROM table this project has located, read directly from rom_profiles.lua.")

----------------------------------------------------------------------
-- 3. Entity struct layout
----------------------------------------------------------------------
local fieldList = {}
for name, offset in pairs(EntityStructLayout.FIELD) do
  fieldList[#fieldList + 1] = { name = name, offset = offset }
end
table.sort(fieldList, function(a, b) return a.offset < b.offset end)
writeJs("entity-struct.js", "ENTITY_STRUCT", {
  base = EntityStructLayout.BASE,
  stride = EntityStructLayout.STRIDE,
  slotCount = EntityStructLayout.SLOT_COUNT,
  playerSlotIndex = EntityStructLayout.PLAYER_SLOT_INDEX_HYPOTHESIS,
  despawnRoutine = EntityStructLayout.DESPAWN_ROUTINE_ADDRESS,
  allocateRoutine = EntityStructLayout.ALLOCATE_ROUTINE_ADDRESS,
  fields = fieldList,
}, "Real, VERIFIED WRAM entity-slot struct -- see src/import/EntityStructLayout.lua's own doc comment.")

----------------------------------------------------------------------
-- 4. Opcode table: real per-opcode decode status, derived by actually
--    building a ScriptRuntime (same stub ctx as scripts/scan_all_scripts
--    .lua) and checking which handler addresses got a real registered
--    Lua implementation -- not hand-classified.
----------------------------------------------------------------------
local opcodeEntries = ScriptOpcodeTable.decode(romData, profile.scriptOpcodeTable)

local stubCtx = setmetatable({
  stats = { curLP = 19, maxLP = 19, curMP = 6, maxMP = 6 },
  flags = { byte = 0 },
  wramBitFlags = { byte = 0 },
  isTriggerEventGateClear = function() return true end,
  onTimerListTest09 = function() return true end,
  onTimerListTest0A = function() return true end,
  runListMatchByte = function() return 0 end,
  isRunListGateSet = function() return true end,
  queue = false,
}, { __index = function() return function() return true end end })
local runtime = ScriptRuntime.new(opcodeEntries, stubCtx)

-- Reverse map: real handler address -> every ScriptOpcodeTable.lua
-- constant name pointing at it (there can be several, e.g. one per
-- sibling opcode in a family) -- this is how each decoded opcode gets
-- a real, code-derived label instead of a hand-typed one.
local addressToNames = {}
for key, value in pairs(ScriptOpcodeTable) do
  if type(value) == "number" and key:match("ADDRESS") then
    addressToNames[value] = addressToNames[value] or {}
    table.insert(addressToNames[value], key)
  end
end
for _, names in pairs(addressToNames) do
  table.sort(names)
end

-- Curated (not code-derived): the small set of handler addresses this
-- project has traced but deliberately left unwired, with why -- see
-- ScriptOpcodeTable.lua's own doc comments at each address for the
-- full disassembly this summarizes.
local KNOWN_HARD = {
  -- REMOVED 2026-08-14 (task #10/"consolidate the last few hours"):
  -- 0x15A4 (opcode 0x80) used to live here ("group value is DATA-
  -- DEPENDENT... no live WRAM simulation to supply") -- that's no
  -- longer true. $02AB (the real leaf behind it) was cracked this same
  -- session (see EntityStructLayout.lua's own PLAYER_FACING_BIT doc
  -- comment and ScriptOpcodeTable.lua's ACTOR_ACTION_HANDLER_ADDRESS_80
  -- entry): it's a plain read of the player's own real facing byte,
  -- which this project DOES already track (Player.lua's `self.facing`)
  -- -- 0x80 is now a real, registered handler and correctly falls out
  -- as `status = "decoded"` below without needing this entry at all.
  [0x10DC] = "Real arithmetic on WRAM $D499/$D49A -- part of the palette/fade-counter family shared with 0xFB/0xBF/0xBD. Not yet decoded to an exact fade curve.",
  [0x1046] = "Third member of the same palette-fade family as 0xBC/0xFB -- reads two real shared gradient lookup tables ($101A/$1030) and writes the result into the pending-palette-write cell or WRAM $D3A3, then calls a further untraced leaf ($1142).",
}

local opcodes = {}
for opcodeIndex = 0, 255 do
  local addr = opcodeEntries[opcodeIndex + 1]
  local status
  if addr == ScriptOpcodeTable.DEFAULT_HANDLER_ADDRESS then
    status = "default"
  elseif runtime.interp.handlers[addr] then
    status = "decoded"
  elseif KNOWN_HARD[addr] then
    status = "known-hard"
  else
    status = "undecoded"
  end
  local names = addressToNames[addr]
  opcodes[#opcodes + 1] = {
    opcode = opcodeIndex,
    handler = addr,
    status = status,
    names = names,
    note = KNOWN_HARD[addr],
  }
end
writeJs("opcodes.js", "OPCODES", opcodes,
  "Real per-opcode decode status for all 256 primary script opcodes -- 'decoded' means ScriptRuntime actually has a registered Lua handler for that real ROM address (checked by building a live ScriptRuntime, not hand-classified); 'default' is the real ROM-confirmed no-op; 'known-hard' is traced but deliberately unwired (see the 'note' field); 'undecoded' is genuinely open.")

----------------------------------------------------------------------
-- 5. Whole-corpus scan results (same method as scripts/scan_all_scripts.lua)
----------------------------------------------------------------------
local spt = profile.scriptPointerTable
local FILLER, CLEAN, HALT_UNDECODED, ERROR_OTHER = "filler", "clean", "halt_undecoded", "error_other"
local haltCounts = {}
local statusCounts = { [FILLER] = 0, [CLEAN] = 0, [HALT_UNDECODED] = 0, [ERROR_OTHER] = 0 }
local stepBudget = 500
for index = 0, spt.recordCount - 1 do
  local resolved = ScriptPointerTable.resolve(romData, spt, index)
  if not resolved then
    statusCounts[FILLER] = statusCounts[FILLER] + 1
  else
    local stream = RomScriptStream.forFileOffset(romData, resolved.bank * 0x4000)
    local shadowRuntime = ScriptRuntime.new(opcodeEntries, stubCtx)
    local ok, err = pcall(function()
      shadowRuntime:run(stream, resolved.cpuAddress, stepBudget)
    end)
    if not ok then
      statusCounts[ERROR_OTHER] = statusCounts[ERROR_OTHER] + 1
    elseif shadowRuntime.stopped then
      local addrHex = tostring(shadowRuntime.stopError):match("real ROM handler (0x%x+)")
      if addrHex then
        statusCounts[HALT_UNDECODED] = statusCounts[HALT_UNDECODED] + 1
        haltCounts[addrHex] = (haltCounts[addrHex] or 0) + 1
      else
        statusCounts[ERROR_OTHER] = statusCounts[ERROR_OTHER] + 1
      end
    else
      statusCounts[CLEAN] = statusCounts[CLEAN] + 1
    end
  end
end
local haltList = {}
for addrHex, count in pairs(haltCounts) do
  local addrNum = tonumber(addrHex)
  haltList[#haltList + 1] = { address = addrHex, count = count, names = addressToNames[addrNum], note = KNOWN_HARD[addrNum] }
end
table.sort(haltList, function(a, b) return a.count > b.count end)
local top = {}
for i = 1, math.min(30, #haltList) do top[i] = haltList[i] end
writeJs("scan-results.js", "SCAN_RESULTS", {
  totalScripts = spt.recordCount,
  stepBudget = stepBudget,
  clean = statusCounts[CLEAN],
  haltUndecoded = statusCounts[HALT_UNDECODED],
  errorOther = statusCounts[ERROR_OTHER],
  filler = statusCounts[FILLER],
  topBlockers = top,
}, "Real, live whole-corpus shadow-run result -- every real scriptPointerTable entry (all 1357), run through the CURRENT opcode coverage. Same method as scripts/scan_all_scripts.lua.")

----------------------------------------------------------------------
-- 6. Room graph
----------------------------------------------------------------------
local rooms = {}
for name, room in pairs(profile.graphics) do
  if type(room) == "table" and room.exits then
    local exits = {}
    for _, exit in ipairs(room.exits) do
      exits[#exits + 1] = {
        status = exit.status,
        targetRoom = exit.targetRoom,
        transitionType = exit.transition and exit.transition.type,
        axis = exit.transition and exit.transition.axis,
        totalPixels = exit.transition and exit.transition.totalPixels,
        reverse = exit.transition and exit.transition.reverse or false,
      }
    end
    local widthTiles, heightTiles
    if room.grid then
      heightTiles = #room.grid
      widthTiles = room.grid[1] and #room.grid[1]
    end
    rooms[#rooms + 1] = { name = name, widthTiles = widthTiles, heightTiles = heightTiles, exits = exits }
  end
end
table.sort(rooms, function(a, b) return a.name < b.name end)
writeJs("rooms.js", "ROOMS", rooms,
  "Every room with real, decoded exits -- read directly from rom_profiles.lua's own graphics.<room>.exits (empirically-found trigger zones + transition shape + target room).")

----------------------------------------------------------------------
-- 6b. Room MAPS (grid + tileOffsets) -- for the Tile/Map viewers. Only
--     the real tile IDS/offsets/grid are exported here; the actual
--     16-byte tile PIXEL data is never embedded -- the viewer decodes
--     it live from a ROM file the user supplies locally in their own
--     browser (this project never ships ROM bytes, same convention as
--     RomLocator.lua elsewhere in the main codebase).
----------------------------------------------------------------------
local roomMaps = {}
for name, room in pairs(profile.graphics) do
  if type(room) == "table" and room.grid and room.tileOffsets then
    local tileOffsets = {}
    for tileId, off in pairs(room.tileOffsets) do
      if type(off) == "string" then
        -- A handful of real tiles are stored as a literal 16-byte
        -- pattern rather than a ROM file offset (e.g. fourthRoom/
        -- sixthRoom's own tile 128, a real known-solid tile with no
        -- single canonical ROM address) -- exported as the raw byte
        -- VALUES so the viewer can render it without needing a ROM
        -- offset to dereference.
        assert(#off == 16, "export_data.lua: literal tile pattern must be exactly 16 bytes")
        local bytes = {}
        for i = 1, 16 do bytes[i] = off:byte(i) end
        tileOffsets[tostring(tileId)] = { literal = bytes }
      else
        tileOffsets[tostring(tileId)] = off
      end
    end
    roomMaps[#roomMaps + 1] = {
      name = name,
      cols = room.grid[1] and #room.grid[1] or 0,
      rows = #room.grid,
      grid = room.grid,
      tileOffsets = tileOffsets,
      floorTileIds = room.floorTileIds,
    }
  end
end
table.sort(roomMaps, function(a, b) return a.name < b.name end)
writeJs("room-maps.js", "ROOM_MAPS", roomMaps,
  "Every real, decoded room/screen tilemap (grid of tile IDs + tile ID -> ROM file offset lookup) -- read directly from rom_profiles.lua's own graphics.<name>.grid/tileOffsets. No tile PIXEL data is embedded -- the Tile/Map viewer pages decode it live from a user-supplied ROM file, entirely client-side.")

----------------------------------------------------------------------
-- 6c. Room CATALOG -- ALL 320 real, individually-decodable bank-5/
--     bank-6 map-table records (2026-08-14, "andere räume, so viele
--     wie möglich, raumdaten reicht"), not just the 8 rooms real
--     gameplay actually reaches. Reuses the EXACT SAME already-tested
--     pipeline `src/app/states/RoomExplorer.lua`'s dev-only F8 browser
--     already drives live in the LÖVE app
--     (`RoomFloorLayout.buildRoomFromMapTableRecord` +
--     `toTileGridBackgroundData`) -- no new discovery here, just
--     exporting an already-verified capability as static site data so
--     it's browsable without a live LÖVE session.
--
--     HONEST SCOPE, UPGRADED 2026-08-14 ("gehe dem map header hinweis
--     nach"): all 320 records now render through `genericCatalogMeta
--     tileTableFileOffset` -- a real, structurally-justified DEFAULT
--     table, not the `unknownRoomACandidates`-borrowed placeholder
--     this export used before. Derivation: `roomSelectorTable`'s own
--     record 0/1 (bank5's and bank6's own "map", VERIFIED via
--     `RoomSelectorTable.resolveMapRoomPointersFileOffset`'s exact
--     byte match to each table's real header) share one real
--     `tileSourcePointer`, cross-checked against the external
--     FFA-Disassembly project's own documented "one tileset per map,
--     no per-room override" US-ROM architecture. Real, but NOT
--     independently ground-truth-verified -- no live gameplay reaches
--     any of these 320 rooms. See rom_profiles.lua's own dated
--     "UPGRADED" doc comments and rom-map.md's "World scope" sections
--     for the full evidence chain, including 2 negative methods tried
--     and ruled out before this one was found.
--
--     `actorAction` field ADDED 2026-08-14 ("verfolge mal diese
--     eventscripte und schaue dir an was diese machen"): each
--     record's own real "header" bytes are now understood to be a
--     genuine per-room EVENT SCRIPT (see MapTable.lua's own "NAMING
--     CORRECTED" doc comment) -- `MapTable.tryDecodeActorAction`
--     extracts the real, already-documented `(group, action)` pair
--     when a record's script matches the ALREADY-KNOWN "ACTOR_ACTION"
--     opcode family (`ScriptOpcodeTable.lua`'s own `ACTOR_ACTION_
--     HANDLER_ADDRESS_*` constants -- a real actor-command-queue
--     mechanism, `$C4E0`/`$C5A0`, per that module's own corrected
--     note -- NOT room-selection, spawn-coordinate, or TILE data).
--     `nil` for the majority of records whose own script doesn't
--     match this specific family (a real, honest "not this family"
--     result, not every room necessarily using it).
----------------------------------------------------------------------
local roomCatalog = {}
local catalogMetatileTableFileOffset =
  profile.roomFloorLayoutPipeline.genericCatalogMetatileTableFileOffset
local function exportCatalogSource(mapTable, sourceLabel)
  local opts = {
    metatileTableFileOffset = catalogMetatileTableFileOffset,
    tilesetFileOffset = mapTable.tilesetFileOffset,
    metatileGridRows = 8,
    metatileGridCols = 10,
  }
  local records = MapTable.decode(romData, mapTable)
  for recordIndex = 0, mapTable.recordCount - 1 do
    local fileOffsetGrid = RoomFloorLayout.buildRoomFromMapTableRecord(romData, mapTable, recordIndex, opts)
    local room = RoomFloorLayout.toTileGridBackgroundData(fileOffsetGrid, opts.tilesetFileOffset)
    local tileOffsets = {}
    for tileId, off in pairs(room.tileOffsets) do
      tileOffsets[tostring(tileId)] = off
    end
    local record = records[recordIndex + 1]
    local actorAction = record and record.header and
      MapTable.tryDecodeActorAction(romData, record.header, opcodeEntries)
    roomCatalog[#roomCatalog + 1] = {
      name = string.format("%s-record-%03d", sourceLabel, recordIndex),
      source = sourceLabel,
      recordIndex = recordIndex,
      cols = room.grid[1] and #room.grid[1] or 0,
      rows = #room.grid,
      grid = room.grid,
      tileOffsets = tileOffsets,
      actorAction = actorAction, -- {group=N, action=N} or nil, see doc comment above
    }
  end
end
exportCatalogSource(profile.mapTable, "bank5")
exportCatalogSource(profile.mapTableBank6, "bank6")
writeJs("room-catalog.js", "ROOM_CATALOG", roomCatalog,
  "ALL 320 real, individually-decodable bank-5 (256 records) + bank-6 (64 records) map-table entries -- the same general pipeline RoomExplorer.lua's dev-only F8 browser already drives live in the LÖVE app, exported here as static data. UPGRADED 2026-08-14: every entry now renders through genericCatalogMetatileTableFileOffset, a real, structurally-derived default (roomSelectorTable's own record 0/1, cross-checked against the external FFA-Disassembly project's documented 'one tileset per map' architecture) -- not the unverified unknownRoomA-borrowed placeholder used before. Still NOT independently ground-truth-verified (no live gameplay reaches these 320 rooms). `actorAction` (added same day): the real (group,action) pair a record's own per-room event script enqueues, when it matches the already-documented ACTOR_ACTION opcode family -- a real actor-command-queue mechanism, NOT tile/graphics data. See rom_profiles.lua's own dated doc comments and rom-map.md's 'World scope' sections for the full evidence chain.")

writeJs("font-tileset.js", "FONT_TILESET", {
  fileOffset = profile.graphics.font.fileOffset,
  bank = profile.graphics.font.bank,
  tileCount = profile.graphics.font.tileCount,
  rowGlyphs = profile.graphics.font.rowGlyphs,
}, "The real, VERIFIED font tileset location -- rom_profiles.lua's own graphics.font.")

----------------------------------------------------------------------
-- 7. Text decoder tables
----------------------------------------------------------------------
local umlauts = {}
for byte, ch in pairs(TextDecoder.UMLAUT_PARTIAL) do
  umlauts[#umlauts + 1] = { byte = byte, char = ch }
end
table.sort(umlauts, function(a, b) return a.byte < b.byte end)
local digraphs = {}
for byte, pair in pairs(TextDecoder.DIGRAPH_PARTIAL) do
  digraphs[#digraphs + 1] = { byte = byte, chars = pair }
end
table.sort(digraphs, function(a, b) return a.byte < b.byte end)

-- Real byte samples straight from the ROM (not hand-typed) -- read
-- until a real TERMINATOR_BYTE (or 40 bytes, as a safety cap) starting
-- at each already-VERIFIED real text file offset.
local function readRealSample(fileOffset, label)
  local bytes = {}
  local i = fileOffset
  while i < #romData and #bytes < 40 do
    local b = romData:byte(i + 1)
    bytes[#bytes + 1] = b
    if b == TextDecoder.TERMINATOR_BYTE then break end
    i = i + 1
  end
  local decoded = TextDecoder.decodeString(romData, fileOffset)
  return { label = label, fileOffset = fileOffset, bytes = bytes, decoded = decoded }
end
local textSamples = {
  readRealSample(profile.messageTextPointer.verifiedExample.textFileOffset,
    "messageID 13 (\"gefunden\" item-pickup text)"),
  readRealSample(0x3A268, "the real dump this project's digraph table was built from (starts on a literal \"WILLY\")"),
  readRealSample(profile.graphics.introText.fileOffset, "intro scroll text"),
}

writeJs("text-decoder.js", "TEXT_DECODER", {
  samples = textSamples,
  mainGlyphs = TextDecoder.MAIN_GLYPHS,
  mainBase = TextDecoder.MAIN_BASE,
  spaceByte = TextDecoder.SPACE_BYTE,
  terminatorByte = TextDecoder.TERMINATOR_BYTE,
  periodByte = TextDecoder.PERIOD_BYTE,
  hyphenByte = TextDecoder.HYPHEN_BYTE,
  newlineByte = TextDecoder.NEWLINE_BYTE,
  exclamationByte = TextDecoder.EXCLAMATION_BYTE,
  questionByte = TextDecoder.QUESTION_BYTE,
  colonByte = TextDecoder.COLON_BYTE,
  umlauts = umlauts,
  digraphs = digraphs,
}, "Real TextDecoder.lua tables -- see that file's own doc comment for how each byte was cross-checked against live-decoded ROM text.")

io.stderr:write("done.\n")
