-- Headless test runner. Run with: luajit tests/run_tests.lua
-- (from the project root -- module paths are require()d as src.* / tests.*).
--
-- No love.* stub needed: every module under src/core, src/import,
-- src/rendering is pure Lua by design (see docs/architecture.md). Exits
-- non-zero on any failure so it's CI-friendly.

require("tests.unit.sha1_test")
require("tests.unit.gbtile_test")
require("tests.unit.state_stack_test")
require("tests.unit.input_test")
require("tests.unit.player_test")
require("tests.unit.stats_test")
require("tests.unit.field_test")
require("tests.unit.field_walkability_test")
require("tests.unit.tile_walkability_test")
require("tests.unit.enemy_test")
require("tests.unit.event_system_test")
require("tests.unit.inventory_test")
require("tests.unit.knockback_flicker_test")
require("tests.unit.combat_formulas_test")
require("tests.unit.combat_noise_test")
require("tests.unit.nibble_packing_test")
require("tests.unit.save_format_test")
require("tests.unit.save_data_test")
require("tests.unit.script_interpreter_test")
require("tests.unit.standard_script_handlers_test")
require("tests.unit.chain_cross_bank_test")
require("tests.unit.rom_script_stream_test")
require("tests.unit.script_runtime_test")
require("tests.unit.boss_sequence_interpreter_test")
require("tests.unit.cut_transition_interpreter_test")
require("tests.unit.enemy_movement_interpreter_test")
require("tests.unit.room_transition_script_test")
require("tests.unit.room_wipe_transition_test")
require("tests.unit.zone_match_test")
require("tests.unit.hold_trigger_test")
require("tests.unit.npc_proximity_test")
require("tests.unit.npc_wander_test")
require("tests.import.rom_identity_test")
require("tests.import.map_table_test")
require("tests.import.room_selector_table_test")
require("tests.import.room_floor_layout_test")
require("tests.import.text_decoder_test")
require("tests.import.item_table_test")
require("tests.import.weapon_table_test")
require("tests.import.lua_writer_test")
require("tests.import.rom_extractor_test")
require("tests.import.dialogue_text_resolver_test")
require("tests.import.generated_cache_test")
require("tests.import.cut_transition_table_test")
require("tests.import.actor_definition_table_test")
require("tests.import.sprite_tile_formula_test")
require("tests.import.noise_table_test")
require("tests.import.enemy_species_table_test")
require("tests.import.enemy_stat_table_test")
require("tests.import.weapon_stat_table_test")
require("tests.import.graphics_candidates_test")
require("tests.import.map_tile_catalog_test")
require("tests.import.script_opcode_table_test")
require("tests.import.rom_profiles_font_test")
require("tests.import.fourth_room_test")
require("tests.import.fifth_room_test")
require("tests.import.sixth_room_test")
require("tests.import.seventh_room_test")
require("tests.import.entity_struct_layout_test")
require("tests.import.script_pointer_table_test")
require("tests.import.message_text_pointer_test")
require("tests.import.tile_landing_position_test")
require("tests.import.npc_catalog_test")
require("tests.import.story_text_test")
require("tests.import.music_decoder_test")
require("tests.audio.gb_square_synth_test")
require("tests.audio.music_score_test")
require("tests.gameplay.boss_encounter_test")

local Harness = require("tests.harness")
local ok = Harness.run()
os.exit(ok and 0 or 1)
