-- RETRACTED 2026-08-19 (same day as added): the seventhRoom ->
-- unknownRoomA_8 -> 9 -> 10 -> 11 -> 12 -> 13 engineering-choice exit
-- chain this file used to test was pulled back after a direct, blunt
-- user report ("alles nach dem 7. raum ist müll und augenscheinlich
-- nicht richtig") triggered a full re-audit. `UNKNOWN_ROOM_A_FLOOR_
-- TILE_IDS` -- the ONLY thing every landing spot in that chain was
-- checked against -- mismatched this project's own stated collision-
-- byte classification rule for 42 of 82 tiles actually used across the
-- 6 rooms. Rebuilding it by applying that rule fully and mechanically
-- (see rom_profiles.lua's own doc comment on `UNKNOWN_ROOM_A_FLOOR_
-- TILE_IDS`) did not fix it -- it revealed a checkerboard artifact with
-- almost no coherent, real-footprint-walkable area in most of the 6
-- rooms (2 of 6 had ZERO connected walkable footprint at all under the
-- corrected rule, using the real 2x2-tile/16x16px footprint
-- `TileWalkability.build` actually checks -- this file's own original
-- test only ever checked a single landing cell, never the real
-- footprint, which is part of why the problem shipped unnoticed).
--
-- See rom_profiles.lua's own doc comment on `seventhRoom.exits` and on
-- `graphics.unknownRoomA_8` for the full add-then-retract story. The
-- room CONTENT (tile-art grids) stays real, decoded ROM data --
-- untouched by this retraction, still tested elsewhere. This file is
-- kept (rather than deleted) purely as an honest record that this was
-- tried and did not hold up, matching this project's own established
-- discipline of recording wrong turns openly (see e.g. the RETRACTED
-- seventhRoom->eighthRoom exit in rom_profiles.lua from 2026-08-17).
--
-- SUPERSEDED, 2026-08-20: `unknownRoomA_8`..`_13` DO have real
-- connectivity again -- built on the FIXED, position-aware collision
-- (`VictorySequence.lua`'s own `unknownRoomA_*` special case) instead of
-- the flawed flat set that broke this attempt, and wired as independent
-- spokes off `worldMapRoom_132` rather than a chain (a systematic
-- edge-match check found 0/16 rows matching for every consecutive pair,
-- so no real evidence supports connecting them to EACH OTHER the way
-- this file's own retracted attempt did). See
-- `tests/import/unknown_room_a_hub_test.lua` for the current, passing
-- tests.
