-- Writes the real generated-cache files this project's own
-- `docs/architecture.md` already names as its committed target
-- architecture (gen1recomp-style: extract once, boot forever after
-- from the cache -- task #34, 2026-08-16).
--
-- Usage: from the repo root,
--   MYSTICQUEST_ROM=/path/to/rom.gb luajit scripts/extract_rom_cache.lua
-- (or drop a ROM at one of the fallback locations below -- same
-- resolution convention as `tests/dev_rom_locator.lua`/
-- `scripts/scan_all_scripts.lua`, duplicated rather than required from
-- `tests/` since that module is explicitly scoped "test-only helper").
--
-- Plain io.*/os.* CLI glue around the pure `RomExtractor`/`LuaWriter`
-- core (same "thin, untested I/O shell around a pure, tested module"
-- split as `SaveFile.lua`) -- this script itself has no test file of
-- its own; `tests/import/rom_extractor_test.lua` covers the real logic,
-- this file only wires stdin-less argv/io glue around it.
--
-- Writes one file per `RomExtractor.STAGES` entry
-- (`data/generated/<stage>.lua`) plus `data/generated/manifest.lua` --
-- all already `.gitignore`'d (`data/generated/`), since generated
-- output embeds directly-extractable copyrighted ROM content and must
-- never be committed.
package.path = "./?.lua;" .. package.path

local RomIdentity = require("src.import.RomIdentity")
local RomProfiles = require("src.import.rom_profiles")
local RomExtractor = require("src.import.RomExtractor")
local LuaWriter = require("src.import.LuaWriter")

local CANDIDATES = {}
CANDIDATES[#CANDIDATES + 1] = os.getenv("MYSTICQUEST_ROM")
CANDIDATES[#CANDIDATES + 1] = "baseroms/Mystic Quest (G) [!].gb"
CANDIDATES[#CANDIDATES + 1] = "../roms/extracted_mq/Mystic Quest (G) [!].gb"
CANDIDATES[#CANDIDATES + 1] = "../baseroms/Mystic Quest (G) [!].gb"

local function findRom()
  for _, path in ipairs(CANDIDATES) do
    if path then
      local f = io.open(path, "rb")
      if f then
        local data = f:read("*a")
        f:close()
        return data, path
      end
    end
  end
  return nil
end

local function writeFile(path, contents)
  local f, err = io.open(path, "wb")
  if not f then
    error(("extract_rom_cache: could not open %q for writing: %s"):format(path, tostring(err)))
  end
  f:write(contents)
  f:close()
end

local romData, romPath = findRom()
if not romData then
  io.stderr:write(
    "extract_rom_cache: no ROM found. Set MYSTICQUEST_ROM=/path/to/rom.gb " ..
    "or place the ROM at one of this script's own fallback locations.\n")
  os.exit(1)
end

print(("extract_rom_cache: using ROM at %s (%d bytes)"):format(romPath, #romData))

local report = RomIdentity.identify(romData)
if report.error then
  io.stderr:write("extract_rom_cache: " .. report.error .. "\n")
  os.exit(1)
end

local profile = RomProfiles.match(report)
if not profile then
  io.stderr:write(("extract_rom_cache: no rom_profiles.lua entry matches this ROM (sha1=%s)\n"):format(report.sha1))
  os.exit(1)
end

print(("extract_rom_cache: matched profile for %q (sha1=%s)"):format(report.title, report.sha1))

local data, manifest = RomExtractor.run(romData, profile)

local outDir = "data/generated"
os.execute('mkdir -p "' .. outDir .. '"')

for _, stage in ipairs(RomExtractor.STAGES) do
  local header = ("-- GENERATED by scripts/extract_rom_cache.lua -- do not edit by hand.\n" ..
    "-- Source ROM sha1: %s (%s)\n" ..
    "-- Regenerate with: MYSTICQUEST_ROM=/path/to/rom.gb luajit scripts/extract_rom_cache.lua"
  ):format(manifest.romSha1, manifest.romTitle)
  local src = LuaWriter.serialize(data[stage.name], header)
  local path = outDir .. "/" .. stage.name .. ".lua"
  writeFile(path, src)
  print(("extract_rom_cache: wrote %s (%d bytes)"):format(path, #src))
end

local manifestHeader = "-- GENERATED by scripts/extract_rom_cache.lua -- do not edit by hand."
local manifestSrc = LuaWriter.serialize(manifest, manifestHeader)
writeFile(outDir .. "/manifest.lua", manifestSrc)
print(("extract_rom_cache: wrote %s/manifest.lua (%d bytes)"):format(outDir, #manifestSrc))

print("extract_rom_cache: done.")
