local Harness = require("tests.harness")
local SaveData = require("src.save.SaveData")
local SaveFormat = require("src.save.SaveFormat")
local Stats = require("src.entities.Stats")

Harness.test("SaveData.serialize: real magic byte and placeholder byte are set correctly", function()
  local stats = Stats.new({ curLP = 19, maxLP = 19, curMP = 6, maxMP = 6, level = 1, gold = 50 })
  local payload = SaveData.serialize(stats, "HELD")
  Harness.assertEqual(#payload, SaveFormat.PAYLOAD_LENGTH)
  Harness.assertEqual(payload[1], SaveFormat.MAGIC_BYTE)
  Harness.assertEqual(payload[124], SaveFormat.LAST_BYTE_PLACEHOLDER)
end)

Harness.test("SaveData.serialize: fails loudly on a missing/empty heroName (no silent placeholder)", function()
  local stats = Stats.new({ curLP = 19, maxLP = 19 })
  Harness.assertTrue(not pcall(SaveData.serialize, stats, nil))
  Harness.assertTrue(not pcall(SaveData.serialize, stats, ""))
end)

Harness.test("SaveData.serialize: fails loudly on a heroName longer than the 16-byte field", function()
  local stats = Stats.new({ curLP = 19, maxLP = 19 })
  local ok = pcall(SaveData.serialize, stats, "ThisNameIsWayTooLong")
  Harness.assertTrue(not ok, "expected serialize to reject an over-length heroName")
end)

Harness.test("SaveData.serialize: reserved bytes [31-123] are explicitly zeroed, not left undefined", function()
  local stats = Stats.new({ curLP = 19, maxLP = 19, curMP = 6, maxMP = 6, level = 1, gold = 50 })
  local payload = SaveData.serialize(stats, "HELD")
  for i = 31, 123 do
    Harness.assertEqual(payload[i], 0, "expected reserved byte " .. i .. " to be zero")
  end
end)

Harness.test("SaveData.serialize/deserialize: round-trips real Stats fields AND heroName exactly", function()
  local stats = Stats.new({ curLP = 13, maxLP = 19, curMP = 4, maxMP = 6, level = 3, gold = 1234, defense = 9 })
  local payload = SaveData.serialize(stats, "Wendel")
  local restored, heroName = SaveData.deserialize(payload)
  Harness.assertEqual(restored.curLP, 13)
  Harness.assertEqual(restored.maxLP, 19)
  Harness.assertEqual(restored.curMP, 4)
  Harness.assertEqual(restored.maxMP, 6)
  Harness.assertEqual(restored.level, 3)
  Harness.assertEqual(restored.gold, 1234)
  Harness.assertEqual(restored.defense, 9)
  Harness.assertEqual(heroName, "Wendel")
end)

Harness.test("SaveData.serialize/deserialize: real u16 fields survive values above 255 (multi-byte, not truncated)", function()
  local stats = Stats.new({ curLP = 300, maxLP = 999, curMP = 0, maxMP = 0, level = 1, gold = 65535 })
  local payload = SaveData.serialize(stats, "HELD")
  local restored = SaveData.deserialize(payload)
  Harness.assertEqual(restored.curLP, 300)
  Harness.assertEqual(restored.maxLP, 999)
  Harness.assertEqual(restored.gold, 65535)
end)

Harness.test("SaveData.serialize/deserialize: a full 16-byte heroName round-trips exactly (field boundary)", function()
  local stats = Stats.new({ curLP = 19, maxLP = 19 })
  local name16 = "ABCDEFGHIJKLMNOP" -- exactly 16 chars
  local payload = SaveData.serialize(stats, name16)
  local _, heroName = SaveData.deserialize(payload)
  Harness.assertEqual(heroName, name16)
end)

Harness.test("SaveData + SaveFormat: full real round-trip through the actual 512-byte SRAM container", function()
  local stats = Stats.new({ curLP = 19, maxLP = 19, curMP = 6, maxMP = 6, level = 1, gold = 50 })
  local payload = SaveData.serialize(stats, "HELD")
  local sram = SaveFormat.encode(payload)
  local decodedPayload, reason = SaveFormat.decode(sram)
  Harness.assertTrue(reason == nil, "unexpected decode failure: " .. tostring(reason))
  local restored, heroName = SaveData.deserialize(decodedPayload)
  local restoredStats = Stats.new(restored)
  Harness.assertEqual(restoredStats.curLP, stats.curLP)
  Harness.assertEqual(restoredStats.maxLP, stats.maxLP)
  Harness.assertEqual(restoredStats.gold, stats.gold)
  Harness.assertEqual(restoredStats.defense, stats.defense)
  Harness.assertEqual(heroName, "HELD")
end)
