local Harness = require("tests.harness")
local ScriptContinuationQueue = require("src.scripting.ScriptContinuationQueue")

Harness.test("ScriptContinuationQueue.new: starts empty", function()
  local q = ScriptContinuationQueue.new()
  Harness.assertTrue(q:isEmpty())
  local shouldRedirect, cursor = q:pop()
  Harness.assertEqual(shouldRedirect, nil)
  Harness.assertEqual(cursor, nil)
end)

Harness.test("ScriptContinuationQueue: push then pop returns the same real entry, FIFO order", function()
  local q = ScriptContinuationQueue.new()
  q:push(true, 100)
  q:push(false, 200)
  Harness.assertTrue(not q:isEmpty())

  local r1, c1 = q:pop()
  Harness.assertTrue(r1)
  Harness.assertEqual(c1, 100)
  Harness.assertTrue(not q:isEmpty()) -- one real entry left

  local r2, c2 = q:pop()
  Harness.assertTrue(not r2)
  Harness.assertEqual(c2, 200)
  Harness.assertTrue(q:isEmpty())
end)

Harness.test("ScriptContinuationQueue: real $D865 counter mirror -- isEmpty tracks push/pop symmetrically", function()
  local q = ScriptContinuationQueue.new()
  Harness.assertTrue(q:isEmpty())
  q:push(true, 1)
  Harness.assertTrue(not q:isEmpty())
  q:pop()
  Harness.assertTrue(q:isEmpty())
end)

Harness.test("ScriptContinuationQueue: popping past empty stays safely empty (no negative count / underflow)", function()
  local q = ScriptContinuationQueue.new()
  q:push(true, 1)
  q:pop()
  local shouldRedirect, cursor = q:pop()
  Harness.assertEqual(shouldRedirect, nil)
  Harness.assertEqual(cursor, nil)
  Harness.assertTrue(q:isEmpty())
end)

Harness.test("ScriptContinuationQueue: interleaved pushes and pops preserve real FIFO order", function()
  local q = ScriptContinuationQueue.new()
  q:push(true, 1)
  local _, c1 = q:pop()
  Harness.assertEqual(c1, 1)
  q:push(false, 2)
  q:push(true, 3)
  local _, c2 = q:pop()
  Harness.assertEqual(c2, 2)
  local _, c3 = q:pop()
  Harness.assertEqual(c3, 3)
  Harness.assertTrue(q:isEmpty())
end)
