local Harness = require("tests.harness")
local Stats = require("src.entities.Stats")

Harness.test("Stats.new: defaults and explicit fields match the verified WRAM layout", function()
  local s = Stats.new({ curLP = 19, maxLP = 19, curMP = 6, maxMP = 6, level = 1, gold = 50 })
  Harness.assertEqual(s.curLP, 19)
  Harness.assertEqual(s.maxLP, 19)
  Harness.assertEqual(s.curMP, 6)
  Harness.assertEqual(s.maxMP, 6)
  Harness.assertEqual(s.level, 1)
  Harness.assertEqual(s.gold, 50)
end)

Harness.test("Stats.new: defense defaults to the real live-captured $D6C3 value (6), explicit value overrides", function()
  local s = Stats.new({ curLP = 19, maxLP = 19 })
  Harness.assertEqual(s.defense, Stats.DEFAULT_DEFENSE)
  Harness.assertEqual(s.defense, 6)
  local s2 = Stats.new({ curLP = 19, maxLP = 19, defense = 10 })
  Harness.assertEqual(s2.defense, 10)
end)

Harness.test("Stats:damage: subtracts and matches the traced 19 -> 16 -> 13 sequence (two 3-point ticks)", function()
  local s = Stats.new({ curLP = 19, maxLP = 19 })
  s:damage(3)
  Harness.assertEqual(s.curLP, 16)
  s:damage(3)
  Harness.assertEqual(s.curLP, 13)
end)

Harness.test("Stats:damage: clamps at 0 rather than going negative (matches ROM $3E30's underflow check)", function()
  local s = Stats.new({ curLP = 5, maxLP = 19 })
  local died = s:damage(9001)
  Harness.assertEqual(s.curLP, 0)
  Harness.assertTrue(died)
end)

Harness.test("Stats:damage: returns false while LP remains above 0", function()
  local s = Stats.new({ curLP = 5, maxLP = 19 })
  local died = s:damage(3)
  Harness.assertTrue(not died)
end)

Harness.test("Stats:isDead: true only at exactly 0", function()
  local s = Stats.new({ curLP = 1, maxLP = 19 })
  Harness.assertTrue(not s:isDead())
  s:damage(1)
  Harness.assertTrue(s:isDead())
end)

Harness.test("Stats:heal: restores LP clamped at maxLP", function()
  local s = Stats.new({ curLP = 5, maxLP = 19 })
  s:heal(3)
  Harness.assertEqual(s.curLP, 8)
  s:heal(9001)
  Harness.assertEqual(s.curLP, 19)
end)
